## Rick and Morty

In [14]:
## import necessary modules
import requests
import time
import pandas as pd
import numpy as np
import urllib.request

In [15]:
## define the base URL for the Rick and Morty API
url = 'http://rickandmortyapi.com/api/'

In [ ]:
## make a GET request to the API
response = requests.get(url)

## check if the request was successful
if response.status_code == 200:
    print("API request successful!") ## print success message, if successful 
    data = response.json() ## parse the JSON response
    print(data) ## print the parsed data
else:
    print("API request failed with status code:", response.status_code) ## print error message, if failed

API request successful!
{'characters': 'https://rickandmortyapi.com/api/character', 'locations': 'https://rickandmortyapi.com/api/location', 'episodes': 'https://rickandmortyapi.com/api/episode'}

In [16]:
## Extracting the available endpoints from the API response
endpoints = list(data.keys())
## Print the endpoints
print(f"Endpoints: {endpoints}")

Endpoints: ['characters', 'locations', 'episodes']

### Rick and Morty - Characters

In [17]:
## Rick and Morty - Characters
characters_endpoint = 'character/'  

r = requests.get(url + characters_endpoint) 

if r.status_code == 200:
    print("API request successful!")
    characters_data = r.json()
    print(characters_data)

API request successful!

In [ ]:
r = requests.get(url + endpoint)

if r.status_code == 200:
    print("API request successful!")
    data = r.json()
    print(data)
else:
    print("API request failed with status code:", r.status_code)

def get_info

API request successful!

In [22]:
## function to get data from a specific endpoint
def get_data(url, endpoint):
    try:
        time.sleep(1)  # to avoid hitting the API rate limit
        r = requests.get(url + endpoint) ## make GET request

        if r.status_code == 200: ## check if request was successful, if so, parse and return JSON data
            print("API request successful!") ## print success message
            return r.json() ## parse and return JSON data
        else:
            print("API request failed with status code:", r.status_code) ## print error message, if failed
            return None ## return None if request failed
    except Exception as e: ## handle exceptions
        print(f"An error occurred while sleeping: {e}") ## print error message

In [23]:
## function to extract and print info from the API response
def get_info(response) -> dict:
    metadata = {}   
    try:
        if response is not None:
            info = response.get('info', {})
            metadata['count'] = info.get('count')
            metadata['pages'] = info.get('pages')
            metadata['next'] = info.get('next')
            metadata['prev'] = info.get('prev')
            return metadata
        else:
            print("No data available to extract info.")
    except Exception as e:
        print(f"An error occurred while extracting info: {e}")

In [26]:
## function to get all pages of results from a paginated endpoint
def get_all_pages(url, endpoint, total_pages): 
    all_results = []
    try:
        for page in range(1, total_pages + 1):
            paged_endpoint = f"{endpoint}?page={page}"
            data = get_data(url, paged_endpoint)
            if data and 'results' in data:
                all_results.extend(data['results'])
        return all_results
    except Exception as e:
        print(f"An error occurred while fetching all pages: {e}")

In [30]:
## function to extract character data from the API response
def get_character_data(characters):
    ## initialize an empty list to store character data
    character_list = [] 
    ## extract relevant fields for each character
    try:
        ## loop through each character in the list
        for character in characters:
            character_info = {
                'id': character.get('id'), ## extract character ID
                'name': character.get('name'), ## extract character name
                'status': character.get('status'), ## extract character status
                'species': character.get('species'), ## extract character species
                'type': character.get('type'), ## extract character type
                'gender': character.get('gender'), ## extract character gender
                'origin_name': character.get('origin', {}).get('name'), ## extract character origin name
                'origin_url': character.get('origin', {}).get('url'), ## extract character origin URL
                'location_name': character.get('location', {}).get('name'), ## extract character location name
                'location_url': character.get('location', {}).get('url'), ## extract character location URL
                'image': character.get('image'), ## extract character image URL
                'episode_count': len(character.get('episode', [])), ## extract number of episodes character appeared in
                'episode': character.get('episode'), ## extract list of episodes character appeared in
                'url': character.get('url'), ## extract character URL
                'created': character.get('created') ## extract character creation date
            }
            
            character_list.append(character_info)
        return character_list
    
    except Exception as e:
        print(f"An error occurred while extracting character data: {e}")

In [33]:
## Get initial data to find total pages
data = get_data(url, characters_endpoint)
## Get metadata from the initial data
meta_data = get_info(data)
## Get total number of pages
total_pages = meta_data.get('pages', 1)
## Get all characters across all pages
all_characters = get_all_pages(url, characters_endpoint, total_pages)
## Extract character data
character_data = get_character_data(all_characters)
## Convert character data to DataFrame for better visualization
character_df = pd.DataFrame(character_data)

API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!

In [94]:
## Export Character DataFrame to Excel
character_df.to_excel('rick_and_morty_character.xlsx', index=False)

### Rick and Morty - Location

In [ ]:
## function to extract location data from the API response 
def get_location_data(locations):
    location_list = [] ## initialize an empty list to store location data
    ## extract relevant fields for each location
    try:
        for location in locations: ## loop through each location in the list
            location_info = {
                'id': location.get('id'), ## extract location ID
                'name': location.get('name'), ## extract location name
                'type': location.get('type'), ## extract location type
                'dimension': location.get('dimension'), ## extract location dimension
                'resident_count': len(location.get('residents', [])), ## extract number of residents in the location
                'residents': location.get('residents'), ## extract list of residents in the location
                'url': location.get('url'), ## extract location URL
                'created': location.get('created') ## extract location creation date
            }
            location_list.append(location_info) ## append location info to the list
        return location_list ## return the list of location data
    except Exception as e: ## handle exceptions
        print(f"An error occurred while extracting location data: {e}") ## print error message if exception occurs

In [50]:
## Rick and Morty - Location 
   
## define location endpoint
location_endpoint = 'location/'
## get initial location data
response = get_data(url, location_endpoint)
## get location metadata
location_info = get_info(response)
## get total number of pages for locations
number_of_pages = location_info.get('pages', 1)
## get all locations across all pages
all_locations = get_all_pages(url, location_endpoint, number_of_pages)
## extract location data
location_data = get_location_data(all_locations)
## convert location data to DataFrame
location_df = pd.DataFrame(location_data)

API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!
API request successful!

In [93]:
## Export Location DataFrame to Excel
location_df.to_excel('rick_and_morty_location.xlsx', index=False)

### Rick and Morty - Episodes

In [65]:
## function to extract episode data from the API response
def get_episode_data(episodes):
    episode_list = [] ## initialize an empty list to store episode data
    ## extract relevant fields for each episode
    try:
        for episode in episodes: ## loop through each episode in the list
            episode_info = {
                'id': episode.get('id'), ## extract episode ID
                'name': episode.get('name'), ## extract episode name
                'air_date': episode.get('air_date'), ## extract air date
                'episode_code': episode.get('episode'), ## extract episode code
                'character_count': len(episode.get('characters', [])), ## extract character count
                'characters': episode.get('characters'), ## extract list of characters in the episode
                'url': episode.get('url'), ## extract episode URL
                'created': episode.get('created') ## extract episode creation date
            }
            episode_list.append(episode_info) ## append episode info to the list
        return episode_list ## return the list of episode data
    except Exception as e: ## handle exceptions
        print(f"An error occurred while extracting episode data: {e}") ## print error message if exception occurs

In [81]:
## Rick and Morty - Episodes
## define episode endpoint
episode_endpoint = 'episode/'
## get initial episode data
response = get_data(url, episode_endpoint)
## get episode metadata
episode_info = get_info(response)
print(f'episode_info: {episode_info}')
## get total number of pages for episodes
number_of_pages = episode_info.get('pages', 1)
## print number of pages for episodes
print(f'number_of_pages: {number_of_pages}')
## get all episodes across all pages
all_episodes = get_all_pages(url, episode_endpoint, number_of_pages)
## extract episode data
episode_data = get_episode_data(all_episodes)
## convert episode data to DataFrame
episode_df = pd.DataFrame(episode_data)

API request successful!
episode_info: {'count': 51, 'pages': 3, 'next': 'https://rickandmortyapi.com/api/episode/?page=2', 'prev': None}
number_of_pages: 3
API request successful!
API request successful!
API request successful!

In [85]:
episode_df.head(1)

,id,name,air_date,episode_code,character_count,characters,url,created
0,1,Pilot,2013-12-02,S01E01,19,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/1,2017-11-10T12:56:33.798Z

In [83]:
episode_df['air_date'] = pd.to_datetime(episode_df['air_date'], format='%B %d, %Y', errors='coerce')

In [86]:
episode_df.head(1)

,id,name,air_date,episode_code,character_count,characters,url,created
0,1,Pilot,2013-12-02,S01E01,19,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/1,2017-11-10T12:56:33.798Z

In [87]:
episode_df['air_year'] = episode_df['air_date'].dt.year
episode_df['air_month'] = episode_df['air_date'].dt.month

In [92]:
## Export Episode DataFrame to Excel
episode_df.to_excel('rick_and_morty_episodes.xlsx', index=False)

In [90]:
episode_df['air_year'].value_counts().sort_index()

air_year
2013     3
2014     8
2015    10
2017    10
2019     5
2020     5
2021    10
Name: count, dtype: int64