## Paginated API

### What is paginated API call?
A paginated API splits large datasets into multiple pages and provides a way to fetch each page sequentially.

### We can extract data from Paginated APIS in four ways
1. Knowing how many pages/requests you will need
2. Doing what the API tells you
3. Going until there are no more results
4. Going until there is an error

In [1]:
## Pokemon API Example
## https://pokeapi.co/api/v2/pokemon?limit=100

In [2]:
## import necessary libraries
import requests
import pandas as pd
import time

In [7]:

## Set the initial URL for the API request
url = "https://pokeapi.co/api/v2/pokemon?limit=100"
## Make the API request and get the data from the first page 
response = requests.get(url)
## Parse the JSON response
data = response.json()

In [9]:
limit = 100
offset = 0
total_pokemons = data['count']
all_pokemons = []

try:

    for i in range(offset, total_pokemons, limit):
        paginated_url = f"https://pokeapi.co/api/v2/pokemon?limit={limit}&offset={i}"
        print(f"Fetching data from: {paginated_url}")
        response = requests.get(paginated_url)
        data = response.json()
        all_pokemons.extend(data['results'])
        time.sleep(1)  # To avoid hitting the API rate limit
except Exception as e:
    print(f"An error occurred: {e}")

Fetching data from: https://pokeapi.co/api/v2/pokemon?limit=100&offset=0
Fetching data from: https://pokeapi.co/api/v2/pokemon?limit=100&offset=100
Fetching data from: https://pokeapi.co/api/v2/pokemon?limit=100&offset=200
Fetching data from: https://pokeapi.co/api/v2/pokemon?limit=100&offset=300
Fetching data from: https://pokeapi.co/api/v2/pokemon?limit=100&offset=400
Fetching data from: https://pokeapi.co/api/v2/pokemon?limit=100&offset=500
Fetching data from: https://pokeapi.co/api/v2/pokemon?limit=100&offset=600
Fetching data from: https://pokeapi.co/api/v2/pokemon?limit=100&offset=700
Fetching data from: https://pokeapi.co/api/v2/pokemon?limit=100&offset=800
Fetching data from: https://pokeapi.co/api/v2/pokemon?limit=100&offset=900
Fetching data from: https://pokeapi.co/api/v2/pokemon?limit=100&offset=1000
Fetching data from: https://pokeapi.co/api/v2/pokemon?limit=100&offset=1100
Fetching data from: https://pokeapi.co/api/v2/pokemon?limit=100&offset=1200
Fetching data from: https://pokeapi.co/api/v2/pokemon?limit=100&offset=1300

In [14]:
## Convert the list of all pokemons to a DataFrame
pokemons_df = pd.DataFrame(all_pokemons)
## Display the first 2 rows of the DataFrame
pokemons_df.head(2)

        name                                   url
0  bulbasaur  https://pokeapi.co/api/v2/pokemon/1/
1    ivysaur  https://pokeapi.co/api/v2/pokemon/2/

In [15]:
pokemons_df.shape

(1350, 2)

In [16]:
### Method: We know how many pages we have method
### Pros: Maybe easy to think about
### Cons: You need to know how many pages it is, not very

## Using to the API

In [20]:
## URL for pagination approach
url = "https://pokeapi.co/api/v2/pokemon?limit=100"

## Initialize an empty list to store all pokemons
all_pokemons = []

##  Using to the API
while url:
    print(f"Fetching data from: {url}")
    response = requests.get(url)
    data = response.json()
    all_pokemons.extend(data['results'])
    url = data.get('next')
    time.sleep(1)  # To avoid hitting the API rate limit

## Convert the list of all pokemons to a DataFrame
pokemons_df = pd.DataFrame(all_pokemons)

Fetching data from: https://pokeapi.co/api/v2/pokemon?limit=100
Fetching data from: https://pokeapi.co/api/v2/pokemon?offset=100&limit=100
Fetching data from: https://pokeapi.co/api/v2/pokemon?offset=200&limit=100
Fetching data from: https://pokeapi.co/api/v2/pokemon?offset=300&limit=100
Fetching data from: https://pokeapi.co/api/v2/pokemon?offset=400&limit=100
Fetching data from: https://pokeapi.co/api/v2/pokemon?offset=500&limit=100
Fetching data from: https://pokeapi.co/api/v2/pokemon?offset=600&limit=100
Fetching data from: https://pokeapi.co/api/v2/pokemon?offset=700&limit=100
Fetching data from: https://pokeapi.co/api/v2/pokemon?offset=800&limit=100
Fetching data from: https://pokeapi.co/api/v2/pokemon?offset=900&limit=100
Fetching data from: https://pokeapi.co/api/v2/pokemon?offset=1000&limit=100
Fetching data from: https://pokeapi.co/api/v2/pokemon?offset=1100&limit=100
Fetching data from: https://pokeapi.co/api/v2/pokemon?offset=1200&limit=100
Fetching data from: https://pokeapi.co/api/v2/pokemon?offset=1300&limit=50

In [21]:
pokemons_df.head(1)

        name                                   url
0  bulbasaur  https://pokeapi.co/api/v2/pokemon/1/

In [ ]:
### Method: Listening to the API
### Pros: The API knows going on inside of it, good if you don't know how many pages / results there are
### Cons: The API has to actually tell you the next page

## Going until there are no more results

In [23]:
## 
pokemon = []
## 
offset = 0
limit = 100

## 
while True:
    print("-----------")
    url = f"https://pokeapi.co/api/v2/pokemon?offset={offset}&limit={limit}"
    print("Requesting", url)
    response = requests.get(url)
    data = response.json()

    if len(data['results']) == 0:
        print("There is no pages further")
        break

    pokemon.extend(data['results'])

    offset += 100

-----------
Requesting https://pokeapi.co/api/v2/pokemon?offset=0&limit=100
-----------
Requesting https://pokeapi.co/api/v2/pokemon?offset=100&limit=100
-----------
Requesting https://pokeapi.co/api/v2/pokemon?offset=200&limit=100
-----------
Requesting https://pokeapi.co/api/v2/pokemon?offset=300&limit=100
-----------
Requesting https://pokeapi.co/api/v2/pokemon?offset=400&limit=100
-----------
Requesting https://pokeapi.co/api/v2/pokemon?offset=500&limit=100
-----------
Requesting https://pokeapi.co/api/v2/pokemon?offset=600&limit=100
-----------
Requesting https://pokeapi.co/api/v2/pokemon?offset=700&limit=100
-----------
Requesting https://pokeapi.co/api/v2/pokemon?offset=800&limit=100
-----------
Requesting https://pokeapi.co/api/v2/pokemon?offset=900&limit=100
-----------
Requesting https://pokeapi.co/api/v2/pokemon?offset=1000&limit=100
-----------
Requesting https://pokeapi.co/api/v2/pokemon?offset=1100&limit=100
-----------
Requesting https://pokeapi.co/api/v2/pokemon?offset=1200&limit=100
-----------
Requesting https://pokeapi.co/api/v2/pokemon?offset=1300&limit=100
-----------
Requesting https://pokeapi.co/api/v2/pokemon?offset=1400&limit=100
There is no pages further

In [26]:
pokemon_df = pd.DataFrame(pokemon)

In [27]:
pokemon_df.head(2)

        name                                   url
0  bulbasaur  https://pokeapi.co/api/v2/pokemon/1/
1    ivysaur  https://pokeapi.co/api/v2/pokemon/2/

In [28]:
### Method: Going until no more results
### Pros: Very flexible
### Cons: Extra requests, doesn't really listen to the API, more line of code

## Waiting until things break

In [29]:
pokemon = []
offset = 0
limit = 100

while True:
    print("----------------")
    url = f"https://pokeapi.co/api/v2/pokemon?offset={offset}&limit={limit}"
    print('Requesting:', url)
    response = requests.get(url)
    data = response.json()

    try:
        print(data['results'][0])
    except Exception as e:
        print(e)
        print("There was an error! Exiting the loop")
        break

    pokemon.extend(data['results'])

    offset += 100

----------------
Requesting: https://pokeapi.co/api/v2/pokemon?offset=0&limit=100
{'name': 'bulbasaur', 'url': 'https://pokeapi.co/api/v2/pokemon/1/'}
----------------
Requesting: https://pokeapi.co/api/v2/pokemon?offset=100&limit=100
{'name': 'electrode', 'url': 'https://pokeapi.co/api/v2/pokemon/101/'}
----------------
Requesting: https://pokeapi.co/api/v2/pokemon?offset=200&limit=100
{'name': 'unown', 'url': 'https://pokeapi.co/api/v2/pokemon/201/'}
----------------
Requesting: https://pokeapi.co/api/v2/pokemon?offset=300&limit=100
{'name': 'delcatty', 'url': 'https://pokeapi.co/api/v2/pokemon/301/'}
----------------
Requesting: https://pokeapi.co/api/v2/pokemon?offset=400&limit=100
{'name': 'kricketot', 'url': 'https://pokeapi.co/api/v2/pokemon/401/'}
----------------
Requesting: https://pokeapi.co/api/v2/pokemon?offset=500&limit=100
{'name': 'oshawott', 'url': 'https://pokeapi.co/api/v2/pokemon/501/'}
----------------
Requesting: https://pokeapi.co/api/v2/pokemon?offset=600&limit=100
{'name': 'klinklang', 'url': 'https://pokeapi.co/api/v2/pokemon/601/'}
----------------
Requesting: https://pokeapi.co/api/v2/pokemon?offset=700&limit=100
{'name': 'hawlucha', 'url': 'https://pokeapi.co/api/v2/pokemon/701/'}
----------------
Requesting: https://pokeapi.co/api/v2/pokemon?offset=800&limit=100
{'name': 'magearna', 'url': 'https://pokeapi.co/api/v2/pokemon/801/'}
----------------
Requesting: https://pokeapi.co/api/v2/pokemon?offset=900&limit=100
{'name': 'ursaluna', 'url': 'https://pokeapi.co/api/v2/pokemon/901/'}
----------------
Requesting: https://pokeapi.co/api/v2/pokemon?offset=1000&limit=100
{'name': 'wo-chien', 'url': 'https://pokeapi.co/api/v2/pokemon/1001/'}
----------------
Requesting: https://pokeapi.co/api/v2/pokemon?offset=1100&limit=100
{'name': 'metagross-mega', 'url': 'https://pokeapi.co/api/v2/pokemon/10076/'}
----------------
Requesting: https://pokeapi.co/api/v2/pokemon?offset=1200&limit=100
{'name': 'darumaka-galar', 'url': 'https://pokeapi.co/api/v2/pokemon/10176/'}
----------------
Requesting: https://pokeapi.co/api/v2/pokemon?offset=1300&limit=100
{'name': 'terapagos-terastal', 'url': 'https://pokeapi.co/api/v2/pokemon/10276/'}
----------------
Requesting: https://pokeapi.co/api/v2/pokemon?offset=1400&limit=100
list index out of range
There was an error! Exiting the loop

In [36]:
pokemon_df = pd.DataFrame(pokemon)

print(pokemon_df.shape)

pokemon_df.tail(5)

(1350, 2)

                         name                                       url
1345            glimmora-mega  https://pokeapi.co/api/v2/pokemon/10321/
1346     tatsugiri-curly-mega  https://pokeapi.co/api/v2/pokemon/10322/
1347    tatsugiri-droopy-mega  https://pokeapi.co/api/v2/pokemon/10323/
1348  tatsugiri-stretchy-mega  https://pokeapi.co/api/v2/pokemon/10324/
1349          baxcalibur-mega  https://pokeapi.co/api/v2/pokemon/10325/

In [37]:
### Method: Wait intil you hit an error with your processing
### Pros: Super easy and flexible, good technique for scraping multiple pages
### Cons: What if there's some OTHER error that isn't a you've run out of data