In [137]:
## Importing Libraries
import pandas as pd
import numpy as np
import os
from datetime import datetime as dt
from pathlib import Path
import re

In [11]:
## Load apple products data file into a DataFrame
df = pd.read_csv('data/apple_products.csv')

In [15]:
## Display the first 5 rows of the DataFrame
df.head(5)

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB

In [18]:
## Display DataFrame information about columns, non-null counts, and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product Name         62 non-null     object
 1   Product URL          62 non-null     object
 2   Brand                62 non-null     object
 3   Sale Price           62 non-null     int64
 4   Mrp                  62 non-null     int64
 5   Discount Percentage  62 non-null     int64
 6   Number Of Ratings    62 non-null     int64
 7   Number Of Reviews    62 non-null     int64
 8   Upc                  62 non-null     object
 9   Star Rating          62 non-null     float64
 10  Ram                  62 non-null     object
dtypes: float64(1), int64(5), object(5)
memory usage: 5.5+ KB

In [23]:
## Get the maximum value in the 'Mrp' column
df['Mrp'].max()

np.int64(149900)

In [25]:
## Get the minimum value in the 'Mrp' column
df['Mrp'].min()

np.int64(39900)

In [26]:
## Calculate the average price of iPhone products
df['Mrp'].mean()

np.float64(88058.06451612903)

In [36]:
## Find the product details with the highest price
df[['Product Name', 'Mrp']][df['Mrp'] == df['Mrp'].max()]

                                  Product Name     Mrp
24        APPLE iPhone 12 Pro (Silver, 512 GB)  149900
41  APPLE iPhone 12 Pro (Pacific Blue, 512 GB)  149900

In [41]:
## Find the product details with the highest price
df.loc[df['Mrp'].eq(df['Mrp'].max()), ['Product Name', 'Mrp']]

                                  Product Name     Mrp
24        APPLE iPhone 12 Pro (Silver, 512 GB)  149900
41  APPLE iPhone 12 Pro (Pacific Blue, 512 GB)  149900

In [46]:
## Find the product details with the lowest price
df.loc[df['Mrp'].eq(df['Mrp'].min()),['Product Name', 'Product URL', 'Mrp', 'Sale Price']]

,Product Name,Product URL,Mrp,Sale Price
52,"APPLE iPhone SE (White, 64 GB)",https://www.flipkart.com/apple-iphone-se-white...,39900,29999
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,39900,29999

In [68]:
## Find the product details with MRP greater than average price of all products
df.loc[df['Mrp'] >= np.round(df['Mrp'].mean()),['Product Name', 'Mrp', 'Sale Price']]

                                        Product Name     Mrp  Sale Price
8                APPLE iPhone XS Max (Silver, 64 GB)   89900       89900
14            APPLE iPhone 11 Pro Max (Gold, 256 GB)  131900      131900
15             APPLE iPhone 11 Pro Max (Gold, 64 GB)  117100      117100
16  APPLE iPhone 11 Pro Max (Midnight Green, 256 GB)  131900      131900
17       APPLE iPhone 11 Pro Max (Space Grey, 64 GB)  117100      117100
18       APPLE iPhone 11 Pro (Midnight Green, 64 GB)  106600       74999
19          APPLE iPhone 11 Pro (Space Grey, 512 GB)  140300      117900
20   APPLE iPhone 11 Pro Max (Midnight Green, 64 GB)  117100      117100
21      APPLE iPhone 11 Pro (Midnight Green, 512 GB)  140300      117900
22          APPLE iPhone 11 Pro (Space Grey, 256 GB)  121300       99900
24              APPLE iPhone 12 Pro (Silver, 512 GB)  149900      140900
25    APPLE iPhone 12 Pro Max (Pacific Blue, 256 GB)  139900      130900
27            APPLE iPhone 12 Pro (Graphite, 256 GB)  129900      120900
30            APPLE iPhone 12 Pro (Graphite, 128 GB)  119900      110900
31        APPLE iPhone 12 Pro Max (Graphite, 256 GB)  139900      130900
32        APPLE iPhone 12 Pro Max (Graphite, 128 GB)  129900      120900
37          APPLE iPhone 12 Pro Max (Silver, 128 GB)  129900      120900
39            APPLE iPhone 12 Pro Max (Gold, 128 GB)  129900      120900
41        APPLE iPhone 12 Pro (Pacific Blue, 512 GB)  149900      140900
46        APPLE iPhone 12 Pro (Pacific Blue, 128 GB)  119900      110900
47    APPLE iPhone 12 Pro Max (Pacific Blue, 128 GB)  129900      120900
48          APPLE iPhone 12 Pro Max (Silver, 256 GB)  139900      130900
49            APPLE iPhone 12 Pro Max (Gold, 256 GB)  139900      130900

In [145]:
## Extract Model Name from Product Name and create a new column 'Model Name'
df['Model Name'] = df['Product Name'].str[6:15].str.upper()

In [146]:
df.head()

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram,Model Name,Model Color,Model Storage
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB,IPHONE 8,Gold,64GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB,IPHONE 8,Space Grey,256GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB,IPHONE 8,Silver,256GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB,IPHONE 8,Silver,256GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB,IPHONE 8,Gold,256GB

In [118]:
## Extract Model Color from Product Name and create a new column 'Model Color'
df['Model Color'] = df['Product Name'].str.split('(').str[1].str.split(',').str[0]

In [138]:
## Extract Model Storage from Product Name and create a new column 'Model Storage' (pattern-based, normalized)
df['Model Storage'] = df['Product Name'].astype(str).str.extract(r'(\d+\s?(?:GB|TB))', flags=re.IGNORECASE)[0].str.upper().str.replace(r'\s+','', regex=True)

In [147]:
## Extrcat Earphodes Inclusion from Product Name and create a new column 'Earphones Included'
df['Earphones Included'] = np.where(df['Product Name'].str.contains('EarPods', case=False, na=False), 'Yes', 'No')

In [152]:
## Extract Power Adapter Inclusion from Product Name and create a new column 'Power Adapter Included'
df['Power Adapter Included'] = np.where(df['Product Name'].str.contains('Power Adapter', case=False, na=False), 'Yes', 'No')

In [159]:
df.head(2)

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram,Model Name,Model Color,Model Storage,Earphones Included,Power Adapter Included
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB,IPHONE 8,Gold,64GB,No,No
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB,IPHONE 8,Space Grey,256GB,No,No