In [29]:
## Import require modules
import pandas as pd

In [30]:
## Load toyota sales data 
sales_data = pd.read_csv('data/toyota_sales_data.csv')

## Load sales rep data
sales_rep = pd.read_csv('data/sales_reps_data.csv')

## <strong>PANDAS SERIES DATATYPE</strong>

In [31]:
sales_data.head(2)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending

In [32]:
model_series = sales_data['car_model']

In [33]:
type(model_series)

pandas.core.series.Series

In [34]:
model_series.head()

0     Tundra
1     Tacoma
2    Corolla
3    Corolla
4     Tundra
Name: car_model, dtype: object

In [35]:
model_series.shape

(5000,)

In [36]:
model_series.index

RangeIndex(start=0, stop=5000, step=1)

In [37]:
model_series.describe()

count     5000
unique       6
top       RAV4
freq       860
Name: car_model, dtype: object

In [38]:
model_series.value_counts()

car_model
RAV4          860
Camry         856
Corolla       827
Tacoma        826
Tundra        817
Highlander    814
Name: count, dtype: int64

In [39]:
model_series.isnull().sum()

np.int64(0)

In [40]:
model_series.nunique()

6

In [41]:
cp_series = sales_data['commission_pct']

In [42]:
cp_series.isnull().sum()

np.int64(1274)

In [43]:
model_series.str.upper()

0        TUNDRA
1        TACOMA
2       COROLLA
3       COROLLA
4        TUNDRA
         ...
4995    COROLLA
4996      CAMRY
4997     TACOMA
4998    COROLLA
4999     TUNDRA
Name: car_model, Length: 5000, dtype: object

## Pandas DataFrames

In [44]:
## Select multiple columns from dataframe
sales_rep[['first_name', 'last_name', 'region']]

     first_name  last_name   region
0       Anthony      Davis    North
1        Edward      Smith    North
2          Paul      Jones     East
3        Robert      Lopez    South
4        Steven     Wilson     West
5         Brian   Martinez     East
6   Christopher      Jones    North
7         David      Davis    North
8        Thomas      Smith     West
9   Christopher      Brown    North
10        David   Gonzalez    North
11       Daniel    Jackson     West
12       Robert  Hernandez    North
13       Daniel   Williams    South
14      William      Moore    North
15      Michael   Martinez     East
16      Charles      Lopez     West
17       Daniel   Martinez    North
18       Thomas     Wilson     East
19       Edward      Jones    North
20          Tom       Kyte  Unknown
21        Scott      Tiger  Unknown

In [47]:
# Find Data Types of Each Column in DataFrame
sales_rep.dtypes

rep_id           int64
first_name      object
last_name       object
email           object
phone_number     int64
hire_date       object
region          object
status          object
dtype: object

In [48]:
sales_data.head(2)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending

In [51]:
# Standarize sales_date column to datetime format
sales_data['sale_date_std'] = pd.to_datetime(sales_data['sale_date'], format='%Y-%m-%d').dt.date

In [52]:
# commision_pct has missing values, fill with 0
sales_data['commission_pct'].fillna(0, inplace=True)

In [54]:
sales_data.head(2)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status,sale_date_std
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed,2024-11-18
1,2,11,2024-11-08,Tacoma,34824.72,0.00,Pending,2024-11-08

In [60]:
# Commission value
sales_data['commission_value'] = round(sales_data['sale_amount'] * sales_data['commission_pct'],2)

In [61]:
sales_data.head()

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status,sale_date_std,commission_value
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed,2024-11-18,2224.84
1,2,11,2024-11-08,Tacoma,34824.72,0.00,Pending,2024-11-08,0.00
2,3,5,2024-11-03,Corolla,20275.08,0.00,Completed,2024-11-03,0.00
3,4,20,2024-11-06,Corolla,20068.93,0.00,Completed,2024-11-06,0.00
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed,2024-11-26,1494.36

In [62]:
sales_rep.head()

,rep_id,first_name,last_name,email,phone_number,hire_date,region,status
0,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active
1,2,Edward,Smith,edward.smith@toyota.com,-10708,12/24/19,North,Active
2,3,Paul,Jones,paul.jones@toyota.com,-2301,9/6/22,East,Active
3,4,Robert,Lopez,robert.lopez@toyota.com,-8631,11/21/20,South,Active
4,5,Steven,Wilson,steven.wilson@toyota.com,-6958,3/17/22,West,Active

In [65]:
# add full_name column to sales_rep dataframe
sales_rep['full_name'] = sales_rep['first_name'] +' '+ sales_rep['last_name']

In [66]:
sales_rep.head()

,rep_id,first_name,last_name,email,phone_number,hire_date,region,status,full_name
0,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,Anthony Davis
1,2,Edward,Smith,edward.smith@toyota.com,-10708,12/24/19,North,Active,Edward Smith
2,3,Paul,Jones,paul.jones@toyota.com,-2301,9/6/22,East,Active,Paul Jones
3,4,Robert,Lopez,robert.lopez@toyota.com,-8631,11/21/20,South,Active,Robert Lopez
4,5,Steven,Wilson,steven.wilson@toyota.com,-6958,3/17/22,West,Active,Steven Wilson

In [69]:
# Standarize hire date column to datetime format
sales_rep['hire_date_std'] = pd.to_datetime(sales_rep['hire_date'], format='%m/%d/%y').dt.date

In [70]:
sales_rep.head()

,rep_id,first_name,last_name,email,phone_number,hire_date,region,status,full_name,hire_date_std
0,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,Anthony Davis,2022-07-21
1,2,Edward,Smith,edward.smith@toyota.com,-10708,12/24/19,North,Active,Edward Smith,2019-12-24
2,3,Paul,Jones,paul.jones@toyota.com,-2301,9/6/22,East,Active,Paul Jones,2022-09-06
3,4,Robert,Lopez,robert.lopez@toyota.com,-8631,11/21/20,South,Active,Robert Lopez,2020-11-21
4,5,Steven,Wilson,steven.wilson@toyota.com,-6958,3/17/22,West,Active,Steven Wilson,2022-03-17

In [73]:
# Create data frame by exlciuding first_name, last_name, and hire_date columns
sales_rep_cleaned = sales_rep.drop(columns=['first_name', 'last_name', 'hire_date'])

## <strong>Accessing Data with loc - label-bsed indexing</strong>

In [83]:
# Accessing the data frame using loc
sales_rep.loc[0:2]

,rep_id,first_name,last_name,email,phone_number,hire_date,region,status,full_name,hire_date_std
0,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,Anthony Davis,2022-07-21
1,2,Edward,Smith,edward.smith@toyota.com,-10708,12/24/19,North,Active,Edward Smith,2019-12-24
2,3,Paul,Jones,paul.jones@toyota.com,-2301,9/6/22,East,Active,Paul Jones,2022-09-06

In [84]:
# Select sepcific columns using loc
sales_rep.loc[:,['full_name', 'region', 'hire_date_std']]

            full_name   region hire_date_std
0       Anthony Davis    North    2022-07-21
1        Edward Smith    North    2019-12-24
2          Paul Jones     East    2022-09-06
3        Robert Lopez    South    2020-11-21
4       Steven Wilson     West    2022-03-17
5      Brian Martinez     East    2023-06-25
6   Christopher Jones    North    2021-02-28
7         David Davis    North    2021-08-29
8        Thomas Smith     West    2022-04-02
9   Christopher Brown    North    2020-08-15
10     David Gonzalez    North    2020-11-11
11     Daniel Jackson     West    2022-08-22
12   Robert Hernandez    North    2023-07-26
13    Daniel Williams    South    2020-09-05
14      William Moore    North    2022-04-07
15   Michael Martinez     East    2022-04-03
16      Charles Lopez     West    2020-05-11
17    Daniel Martinez    North    2021-05-06
18      Thomas Wilson     East    2020-09-04
19       Edward Jones    North    2020-07-09
20           Tom Kyte  Unknown    2022-07-25
21        Scott Tiger  Unknown    2022-03-23

In [93]:
sales_data.loc[sales_data['sale_amount'] > 30000, ['sale_rep_id', 'car_model', 'sale_amount', 'commission_value', 'sale_date_std']]

      sale_rep_id   car_model  sale_amount  commission_value sale_date_std
0              16      Tundra     44496.88           2224.84    2024-11-18
1              11      Tacoma     34824.72              0.00    2024-11-08
4               1      Tundra     49811.99           1494.36    2024-11-26
5              14        RAV4     34346.20           1030.39    2024-11-28
6              12        RAV4     33073.24            992.20    2024-11-30
...           ...         ...          ...               ...           ...
4990           20  Highlander     36500.60              0.00    2024-11-17
4992           10      Tundra     47497.87            949.96    2024-11-26
4994           12      Tundra     41202.36            824.05    2024-11-01
4997           18      Tacoma     30780.39            615.61    2024-11-06
4999           13      Tundra     44525.85              0.00    2024-11-21

[2976 rows x 5 columns]

In [98]:
# Find a trnsaction value more than 30000 and car model sould be 'RAV4'
sales_data.loc[
                (sales_data['sale_amount'] > 30000) & (sales_data['car_model'] == 'RAV4'), 
               ['sale_rep_id', 'car_model', 'sale_amount', 'commission_value', 'sale_date_std']
               ]

      sale_rep_id car_model  sale_amount  commission_value sale_date_std
5              14      RAV4     34346.20           1030.39    2024-11-28
6              12      RAV4     33073.24            992.20    2024-11-30
17              8      RAV4     32751.81              0.00    2024-11-02
21             14      RAV4     31273.79           1563.69    2024-11-21
28              2      RAV4     30624.47              0.00    2024-11-19
...           ...       ...          ...               ...           ...
4967           12      RAV4     32327.35              0.00    2024-11-14
4971           16      RAV4     31604.19            632.08    2024-11-22
4979           12      RAV4     30446.63            608.93    2024-11-21
4980           19      RAV4     30452.77           1522.64    2024-11-01
4988           20      RAV4     31543.36            630.87    2024-11-04

[519 rows x 5 columns]

In [111]:
# Update commission_pct to 0.05 where carmodel is 'RAV4' and commission_pct is 0
sales_data.loc[
        (sales_data['car_model'] == 'RAV4') & 
        (sales_data['commission_pct'] == 0.0) & 
        (sales_data['sale_amount'] > 30000) &
        (sales_data['sale_status'] == 'Completed'),
        'commission_pct'
        ] = 0.05

In [112]:
sales_data

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status,sale_date_std,commission_value
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed,2024-11-18,2224.84
1,2,11,2024-11-08,Tacoma,34824.72,0.00,Pending,2024-11-08,0.00
2,3,5,2024-11-03,Corolla,20275.08,0.00,Completed,2024-11-03,0.00
3,4,20,2024-11-06,Corolla,20068.93,0.00,Completed,2024-11-06,0.00
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed,2024-11-26,1494.36
...,...,...,...,...,...,...,...,...,...
4995,4996,1,2024-11-06,Corolla,21484.83,0.05,Completed,2024-11-06,1074.24
4996,4997,8,2024-11-11,Camry,26519.24,0.05,Pending,2024-11-11,1325.96
4997,4998,18,2024-11-06,Tacoma,30780.39,0.02,Completed,2024-11-06,615.61
4998,4999,10,2024-11-21,Corolla,22654.59,0.00,Completed,2024-11-21,0.00
4999,5000,13,2024-11-21,Tundra,44525.85,0.00,Cancelled,2024-11-21,0.00

## <strong>Accessing Data with iloc - Position-Based Indexing</strong>

. iloc is used to access the data frame by position instead of label
. Along with index value, we can also pass column positions

In [117]:
# access the data frame using iloc 
# column and row by index position
sales_data.iloc[0:5, 0:5]

   sale_id  sale_rep_id   sale_date car_model  sale_amount
0        1           16  2024-11-18    Tundra     44496.88
1        2           11  2024-11-08    Tacoma     34824.72
2        3            5  2024-11-03   Corolla     20275.08
3        4           20  2024-11-06   Corolla     20068.93
4        5            1  2024-11-26    Tundra     49811.99

In [120]:
# display the fifth row values using iloc
sales_data.iloc[4, 0:5]

sale_id                 5
sale_rep_id             1
sale_date      2024-11-26
car_model          Tundra
sale_amount      49811.99
Name: 4, dtype: object

## <strong>Comparing loc and iloc methods</strong>

In [128]:
# loc: label based indexing
sales_data.loc[2:10, ['sale_rep_id', 'car_model', 'sale_amount', 'commission_value', 'sale_date_std']]

    sale_rep_id   car_model  sale_amount  commission_value sale_date_std
2             5     Corolla     20275.08              0.00    2024-11-03
3            20     Corolla     20068.93              0.00    2024-11-06
4             1      Tundra     49811.99           1494.36    2024-11-26
5            14        RAV4     34346.20           1030.39    2024-11-28
6            12        RAV4     33073.24            992.20    2024-11-30
7             3       Camry     25561.86              0.00    2024-11-05
8             9        RAV4     29690.54            890.72    2024-11-25
9            14       Camry     27321.71            819.65    2024-11-09
10           12  Highlander     40044.87            800.90    2024-11-11

In [141]:
# iloc: position based indexing
sales_data.iloc[2:10, [1, 3, 4, 8, 7]]

   sale_rep_id car_model  sale_amount  commission_value sale_date_std
2            5   Corolla     20275.08              0.00    2024-11-03
3           20   Corolla     20068.93              0.00    2024-11-06
4            1    Tundra     49811.99           1494.36    2024-11-26
5           14      RAV4     34346.20           1030.39    2024-11-28
6           12      RAV4     33073.24            992.20    2024-11-30
7            3     Camry     25561.86              0.00    2024-11-05
8            9      RAV4     29690.54            890.72    2024-11-25
9           14     Camry     27321.71            819.65    2024-11-09

In [121]:
# loc: label based indexing
# Select sales data, where sale amount is greater than 30000
sales_data.loc[sales_data[
    'sale_amount'] > 30000,
    ['sale_rep_id', 'car_model', 'sale_amount', 'commission_value', 'sale_date_std']
               ]
# iloc: position based indexing

      sale_rep_id   car_model  sale_amount  commission_value sale_date_std
0              16      Tundra     44496.88           2224.84    2024-11-18
1              11      Tacoma     34824.72              0.00    2024-11-08
4               1      Tundra     49811.99           1494.36    2024-11-26
5              14        RAV4     34346.20           1030.39    2024-11-28
6              12        RAV4     33073.24            992.20    2024-11-30
...           ...         ...          ...               ...           ...
4990           20  Highlander     36500.60              0.00    2024-11-17
4992           10      Tundra     47497.87            949.96    2024-11-26
4994           12      Tundra     41202.36            824.05    2024-11-01
4997           18      Tacoma     30780.39            615.61    2024-11-06
4999           13      Tundra     44525.85              0.00    2024-11-21

[2976 rows x 5 columns]

## <strong>Data Cleaning and Preprocessing using Pandas</strong>

## Handle Missing Data in Data-Frame: fillna & dropna

In [150]:
# load sales data
sales_df = pd.read_csv('data/toyota_sales_data.csv', low_memory=False)

# load sales rep data
sales_rep = pd.read_csv('data/sales_reps_data.csv', low_memory=False)

In [155]:
# find missing values in sales data dataframe
sales_df.isnull().sum()

sale_id              0
sale_rep_id          0
sale_date            0
car_model            0
sale_amount          0
commission_pct    1274
sale_status          0
dtype: int64

In [156]:
# Find missing values in sales rep data dataframe
sales_rep.isnull().sum()

rep_id          0
first_name      0
last_name       0
email           0
phone_number    0
hire_date       0
region          0
status          0
dtype: int64

In [157]:
# find the data types of each column in sales data dataframe
sales_df.dtypes

sale_id             int64
sale_rep_id         int64
sale_date          object
car_model          object
sale_amount       float64
commission_pct    float64
sale_status        object
dtype: object

In [163]:
# fill the missing values in commission_pct column with 0.00
sales_df['commission_pct'] = sales_df['commission_pct'].fillna(0.00)

In [164]:
# print sample data after filling missing values
sales_df.head()

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,0.00,Pending
2,3,5,2024-11-03,Corolla,20275.08,0.00,Completed
3,4,20,2024-11-06,Corolla,20068.93,0.00,Completed
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed

In [165]:
# checking missing values after filling
sales_df.isnull().sum()

sale_id           0
sale_rep_id       0
sale_date         0
car_model         0
sale_amount       0
commission_pct    0
sale_status       0
dtype: int64

In [166]:
# drop the columns with more than 50% missing values
sales_df.dropna(thresh=len(sales_df)*0.5, axis=1, inplace=True)

In [167]:
sales_df.shape

(5000, 7)

In [168]:
# Load sales data
sales_df = pd.read_csv('data/toyota_sales_data.csv', low_memory=False)

In [171]:
# drop the rows with missing values in commission_pct column
sales_df = sales_df.dropna(subset=['commission_pct'])

sales_df.shape

(3726, 7)

In [172]:
# load sales data
sales_df = pd.read_csv('data/toyota_sales_data.csv', low_memory=False)

In [175]:
# filling missing values in commission_pct column in statistical way
print('median of commission_pct column:', sales_df['commission_pct'].median())
print()
print('mean of commission_pct column:', sales_df['commission_pct'].mean())
print()
print('mode of commission_pct column:', sales_df['commission_pct'].mode()[0])

median of commission_pct column: 0.03

mean of commission_pct column: 0.03372517444981213

mode of commission_pct column: 0.05

In [ ]:
# Fill missing values in commission_pct column with median value
median_commission = sales_df['commission_pct'].median
print('median commission value:', median_commission)