In [1]:
## Import require modules
import pandas as pd

In [2]:
## Load toyota sales data 
sales_data = pd.read_csv('data/toyota_sales_data.csv')

## Load sales rep data
sales_rep = pd.read_csv('data/sales_reps_data.csv')

## <strong>PANDAS SERIES DATATYPE</strong>

In [3]:
sales_data.head(2)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending

In [4]:
model_series = sales_data['car_model']

In [5]:
type(model_series)

pandas.core.series.Series

In [6]:
model_series.head()

0     Tundra
1     Tacoma
2    Corolla
3    Corolla
4     Tundra
Name: car_model, dtype: object

In [7]:
model_series.shape

(5000,)

In [8]:
model_series.index

RangeIndex(start=0, stop=5000, step=1)

In [9]:
model_series.describe()

count     5000
unique       6
top       RAV4
freq       860
Name: car_model, dtype: object

In [10]:
model_series.value_counts()

car_model
RAV4          860
Camry         856
Corolla       827
Tacoma        826
Tundra        817
Highlander    814
Name: count, dtype: int64

In [11]:
model_series.isnull().sum()

np.int64(0)

In [12]:
model_series.nunique()

6

In [13]:
cp_series = sales_data['commission_pct']

In [14]:
cp_series.isnull().sum()

np.int64(1274)

In [15]:
model_series.str.upper()

0        TUNDRA
1        TACOMA
2       COROLLA
3       COROLLA
4        TUNDRA
         ...
4995    COROLLA
4996      CAMRY
4997     TACOMA
4998    COROLLA
4999     TUNDRA
Name: car_model, Length: 5000, dtype: object

## Pandas DataFrames

In [16]:
## Select multiple columns from dataframe
sales_rep[['first_name', 'last_name', 'region']]

     first_name  last_name   region
0       Anthony      Davis    North
1        Edward      Smith    North
2          Paul      Jones     East
3        Robert      Lopez    South
4        Steven     Wilson     West
5         Brian   Martinez     East
6   Christopher      Jones    North
7         David      Davis    North
8        Thomas      Smith     West
9   Christopher      Brown    North
10        David   Gonzalez    North
11       Daniel    Jackson     West
12       Robert  Hernandez    North
13       Daniel   Williams    South
14      William      Moore    North
15      Michael   Martinez     East
16      Charles      Lopez     West
17       Daniel   Martinez    North
18       Thomas     Wilson     East
19       Edward      Jones    North
20          Tom       Kyte  Unknown
21        Scott      Tiger  Unknown

In [17]:
# Find Data Types of Each Column in DataFrame
sales_rep.dtypes

rep_id           int64
first_name      object
last_name       object
email           object
phone_number     int64
hire_date       object
region          object
status          object
dtype: object

In [18]:
sales_data.head(2)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending

In [19]:
# Standarize sales_date column to datetime format
sales_data['sale_date_std'] = pd.to_datetime(sales_data['sale_date'], format='%Y-%m-%d').dt.date

In [20]:
# commision_pct has missing values, fill with 0
sales_data['commission_pct'].fillna(0, inplace=True)

In [21]:
sales_data.head(2)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status,sale_date_std
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed,2024-11-18
1,2,11,2024-11-08,Tacoma,34824.72,0.00,Pending,2024-11-08

In [22]:
# Commission value
sales_data['commission_value'] = round(sales_data['sale_amount'] * sales_data['commission_pct'],2)

In [23]:
sales_data.head()

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status,sale_date_std,commission_value
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed,2024-11-18,2224.84
1,2,11,2024-11-08,Tacoma,34824.72,0.00,Pending,2024-11-08,0.00
2,3,5,2024-11-03,Corolla,20275.08,0.00,Completed,2024-11-03,0.00
3,4,20,2024-11-06,Corolla,20068.93,0.00,Completed,2024-11-06,0.00
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed,2024-11-26,1494.36

In [24]:
sales_rep.head()

,rep_id,first_name,last_name,email,phone_number,hire_date,region,status
0,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active
1,2,Edward,Smith,edward.smith@toyota.com,-10708,12/24/19,North,Active
2,3,Paul,Jones,paul.jones@toyota.com,-2301,9/6/22,East,Active
3,4,Robert,Lopez,robert.lopez@toyota.com,-8631,11/21/20,South,Active
4,5,Steven,Wilson,steven.wilson@toyota.com,-6958,3/17/22,West,Active

In [25]:
# add full_name column to sales_rep dataframe
sales_rep['full_name'] = sales_rep['first_name'] +' '+ sales_rep['last_name']

In [26]:
sales_rep.head()

,rep_id,first_name,last_name,email,phone_number,hire_date,region,status,full_name
0,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,Anthony Davis
1,2,Edward,Smith,edward.smith@toyota.com,-10708,12/24/19,North,Active,Edward Smith
2,3,Paul,Jones,paul.jones@toyota.com,-2301,9/6/22,East,Active,Paul Jones
3,4,Robert,Lopez,robert.lopez@toyota.com,-8631,11/21/20,South,Active,Robert Lopez
4,5,Steven,Wilson,steven.wilson@toyota.com,-6958,3/17/22,West,Active,Steven Wilson

In [27]:
# Standarize hire date column to datetime format
sales_rep['hire_date_std'] = pd.to_datetime(sales_rep['hire_date'], format='%m/%d/%y').dt.date

In [28]:
sales_rep.head()

,rep_id,first_name,last_name,email,phone_number,hire_date,region,status,full_name,hire_date_std
0,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,Anthony Davis,2022-07-21
1,2,Edward,Smith,edward.smith@toyota.com,-10708,12/24/19,North,Active,Edward Smith,2019-12-24
2,3,Paul,Jones,paul.jones@toyota.com,-2301,9/6/22,East,Active,Paul Jones,2022-09-06
3,4,Robert,Lopez,robert.lopez@toyota.com,-8631,11/21/20,South,Active,Robert Lopez,2020-11-21
4,5,Steven,Wilson,steven.wilson@toyota.com,-6958,3/17/22,West,Active,Steven Wilson,2022-03-17

In [29]:
# Create data frame by exlciuding first_name, last_name, and hire_date columns
sales_rep_cleaned = sales_rep.drop(columns=['first_name', 'last_name', 'hire_date'])

## <strong>Accessing Data with loc - label-bsed indexing</strong>

In [30]:
# Accessing the data frame using loc
sales_rep.loc[0:2]

,rep_id,first_name,last_name,email,phone_number,hire_date,region,status,full_name,hire_date_std
0,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,Anthony Davis,2022-07-21
1,2,Edward,Smith,edward.smith@toyota.com,-10708,12/24/19,North,Active,Edward Smith,2019-12-24
2,3,Paul,Jones,paul.jones@toyota.com,-2301,9/6/22,East,Active,Paul Jones,2022-09-06

In [31]:
# Select sepcific columns using loc
sales_rep.loc[:,['full_name', 'region', 'hire_date_std']]

            full_name   region hire_date_std
0       Anthony Davis    North    2022-07-21
1        Edward Smith    North    2019-12-24
2          Paul Jones     East    2022-09-06
3        Robert Lopez    South    2020-11-21
4       Steven Wilson     West    2022-03-17
5      Brian Martinez     East    2023-06-25
6   Christopher Jones    North    2021-02-28
7         David Davis    North    2021-08-29
8        Thomas Smith     West    2022-04-02
9   Christopher Brown    North    2020-08-15
10     David Gonzalez    North    2020-11-11
11     Daniel Jackson     West    2022-08-22
12   Robert Hernandez    North    2023-07-26
13    Daniel Williams    South    2020-09-05
14      William Moore    North    2022-04-07
15   Michael Martinez     East    2022-04-03
16      Charles Lopez     West    2020-05-11
17    Daniel Martinez    North    2021-05-06
18      Thomas Wilson     East    2020-09-04
19       Edward Jones    North    2020-07-09
20           Tom Kyte  Unknown    2022-07-25
21        Scott Tiger  Unknown    2022-03-23

In [32]:
sales_data.loc[sales_data['sale_amount'] > 30000, ['sale_rep_id', 'car_model', 'sale_amount', 'commission_value', 'sale_date_std']]

      sale_rep_id   car_model  sale_amount  commission_value sale_date_std
0              16      Tundra     44496.88           2224.84    2024-11-18
1              11      Tacoma     34824.72              0.00    2024-11-08
4               1      Tundra     49811.99           1494.36    2024-11-26
5              14        RAV4     34346.20           1030.39    2024-11-28
6              12        RAV4     33073.24            992.20    2024-11-30
...           ...         ...          ...               ...           ...
4990           20  Highlander     36500.60              0.00    2024-11-17
4992           10      Tundra     47497.87            949.96    2024-11-26
4994           12      Tundra     41202.36            824.05    2024-11-01
4997           18      Tacoma     30780.39            615.61    2024-11-06
4999           13      Tundra     44525.85              0.00    2024-11-21

[2976 rows x 5 columns]

In [33]:
# Find a trnsaction value more than 30000 and car model sould be 'RAV4'
sales_data.loc[
                (sales_data['sale_amount'] > 30000) & (sales_data['car_model'] == 'RAV4'), 
               ['sale_rep_id', 'car_model', 'sale_amount', 'commission_value', 'sale_date_std']
               ]

      sale_rep_id car_model  sale_amount  commission_value sale_date_std
5              14      RAV4     34346.20           1030.39    2024-11-28
6              12      RAV4     33073.24            992.20    2024-11-30
17              8      RAV4     32751.81              0.00    2024-11-02
21             14      RAV4     31273.79           1563.69    2024-11-21
28              2      RAV4     30624.47              0.00    2024-11-19
...           ...       ...          ...               ...           ...
4967           12      RAV4     32327.35              0.00    2024-11-14
4971           16      RAV4     31604.19            632.08    2024-11-22
4979           12      RAV4     30446.63            608.93    2024-11-21
4980           19      RAV4     30452.77           1522.64    2024-11-01
4988           20      RAV4     31543.36            630.87    2024-11-04

[519 rows x 5 columns]

In [34]:
# Update commission_pct to 0.05 where carmodel is 'RAV4' and commission_pct is 0
sales_data.loc[
        (sales_data['car_model'] == 'RAV4') & 
        (sales_data['commission_pct'] == 0.0) & 
        (sales_data['sale_amount'] > 30000) &
        (sales_data['sale_status'] == 'Completed'),
        'commission_pct'
        ] = 0.05

In [35]:
sales_data

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status,sale_date_std,commission_value
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed,2024-11-18,2224.84
1,2,11,2024-11-08,Tacoma,34824.72,0.00,Pending,2024-11-08,0.00
2,3,5,2024-11-03,Corolla,20275.08,0.00,Completed,2024-11-03,0.00
3,4,20,2024-11-06,Corolla,20068.93,0.00,Completed,2024-11-06,0.00
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed,2024-11-26,1494.36
...,...,...,...,...,...,...,...,...,...
4995,4996,1,2024-11-06,Corolla,21484.83,0.05,Completed,2024-11-06,1074.24
4996,4997,8,2024-11-11,Camry,26519.24,0.05,Pending,2024-11-11,1325.96
4997,4998,18,2024-11-06,Tacoma,30780.39,0.02,Completed,2024-11-06,615.61
4998,4999,10,2024-11-21,Corolla,22654.59,0.00,Completed,2024-11-21,0.00
4999,5000,13,2024-11-21,Tundra,44525.85,0.00,Cancelled,2024-11-21,0.00

## <strong>Accessing Data with iloc - Position-Based Indexing</strong>

. iloc is used to access the data frame by position instead of label
. Along with index value, we can also pass column positions

In [36]:
# access the data frame using iloc 
# column and row by index position
sales_data.iloc[0:5, 0:5]

   sale_id  sale_rep_id   sale_date car_model  sale_amount
0        1           16  2024-11-18    Tundra     44496.88
1        2           11  2024-11-08    Tacoma     34824.72
2        3            5  2024-11-03   Corolla     20275.08
3        4           20  2024-11-06   Corolla     20068.93
4        5            1  2024-11-26    Tundra     49811.99

In [37]:
# display the fifth row values using iloc
sales_data.iloc[4, 0:5]

sale_id                 5
sale_rep_id             1
sale_date      2024-11-26
car_model          Tundra
sale_amount      49811.99
Name: 4, dtype: object

## <strong>Comparing loc and iloc methods</strong>

In [38]:
# loc: label based indexing
sales_data.loc[2:10, ['sale_rep_id', 'car_model', 'sale_amount', 'commission_value', 'sale_date_std']]

    sale_rep_id   car_model  sale_amount  commission_value sale_date_std
2             5     Corolla     20275.08              0.00    2024-11-03
3            20     Corolla     20068.93              0.00    2024-11-06
4             1      Tundra     49811.99           1494.36    2024-11-26
5            14        RAV4     34346.20           1030.39    2024-11-28
6            12        RAV4     33073.24            992.20    2024-11-30
7             3       Camry     25561.86              0.00    2024-11-05
8             9        RAV4     29690.54            890.72    2024-11-25
9            14       Camry     27321.71            819.65    2024-11-09
10           12  Highlander     40044.87            800.90    2024-11-11

In [39]:
# iloc: position based indexing
sales_data.iloc[2:10, [1, 3, 4, 8, 7]]

   sale_rep_id car_model  sale_amount  commission_value sale_date_std
2            5   Corolla     20275.08              0.00    2024-11-03
3           20   Corolla     20068.93              0.00    2024-11-06
4            1    Tundra     49811.99           1494.36    2024-11-26
5           14      RAV4     34346.20           1030.39    2024-11-28
6           12      RAV4     33073.24            992.20    2024-11-30
7            3     Camry     25561.86              0.00    2024-11-05
8            9      RAV4     29690.54            890.72    2024-11-25
9           14     Camry     27321.71            819.65    2024-11-09

In [40]:
# loc: label based indexing
# Select sales data, where sale amount is greater than 30000
sales_data.loc[sales_data[
    'sale_amount'] > 30000,
    ['sale_rep_id', 'car_model', 'sale_amount', 'commission_value', 'sale_date_std']
               ]
# iloc: position based indexing

      sale_rep_id   car_model  sale_amount  commission_value sale_date_std
0              16      Tundra     44496.88           2224.84    2024-11-18
1              11      Tacoma     34824.72              0.00    2024-11-08
4               1      Tundra     49811.99           1494.36    2024-11-26
5              14        RAV4     34346.20           1030.39    2024-11-28
6              12        RAV4     33073.24            992.20    2024-11-30
...           ...         ...          ...               ...           ...
4990           20  Highlander     36500.60              0.00    2024-11-17
4992           10      Tundra     47497.87            949.96    2024-11-26
4994           12      Tundra     41202.36            824.05    2024-11-01
4997           18      Tacoma     30780.39            615.61    2024-11-06
4999           13      Tundra     44525.85              0.00    2024-11-21

[2976 rows x 5 columns]

## <strong>Data Cleaning and Preprocessing using Pandas</strong>

## Handle Missing Data in Data-Frame: fillna & dropna

In [41]:
# load sales data
sales_df = pd.read_csv('data/toyota_sales_data.csv', low_memory=False)

# load sales rep data
sales_rep = pd.read_csv('data/sales_reps_data.csv', low_memory=False)

In [42]:
# find missing values in sales data dataframe
sales_df.isnull().sum()

sale_id              0
sale_rep_id          0
sale_date            0
car_model            0
sale_amount          0
commission_pct    1274
sale_status          0
dtype: int64

In [43]:
# Find missing values in sales rep data dataframe
sales_rep.isnull().sum()

rep_id          0
first_name      0
last_name       0
email           0
phone_number    0
hire_date       0
region          0
status          0
dtype: int64

In [44]:
# find the data types of each column in sales data dataframe
sales_df.dtypes

sale_id             int64
sale_rep_id         int64
sale_date          object
car_model          object
sale_amount       float64
commission_pct    float64
sale_status        object
dtype: object

In [45]:
# fill the missing values in commission_pct column with 0.00
sales_df['commission_pct'] = sales_df['commission_pct'].fillna(0.00)

In [46]:
# print sample data after filling missing values
sales_df.head()

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,0.00,Pending
2,3,5,2024-11-03,Corolla,20275.08,0.00,Completed
3,4,20,2024-11-06,Corolla,20068.93,0.00,Completed
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed

In [47]:
# checking missing values after filling
sales_df.isnull().sum()

sale_id           0
sale_rep_id       0
sale_date         0
car_model         0
sale_amount       0
commission_pct    0
sale_status       0
dtype: int64

In [48]:
# drop the columns with more than 50% missing values
sales_df.dropna(thresh=len(sales_df)*0.5, axis=1, inplace=True)

In [49]:
sales_df.shape

(5000, 7)

In [50]:
# Load sales data
sales_df = pd.read_csv('data/toyota_sales_data.csv', low_memory=False)

In [51]:
# drop the rows with missing values in commission_pct column
sales_df = sales_df.dropna(subset=['commission_pct'])

sales_df.shape

(3726, 7)

In [52]:
# load sales data
sales_df = pd.read_csv('data/toyota_sales_data.csv', low_memory=False)

In [53]:
# filling missing values in commission_pct column in statistical way
print('median of commission_pct column:', sales_df['commission_pct'].median())
print()
print('mean of commission_pct column:', sales_df['commission_pct'].mean())
print()
print('mode of commission_pct column:', sales_df['commission_pct'].mode()[0])

median of commission_pct column: 0.03

mean of commission_pct column: 0.03372517444981213

mode of commission_pct column: 0.05

In [57]:
# Fill missing values in commission_pct column with median value
# Calulate median value
median_commission = sales_df['commission_pct'].median()
print('median commission value:', median_commission)
print()
# Fill missing values with median value
sales_df['commission_pct'] = sales_df['commission_pct'].fillna(median_commission)

median commission value: 0.03

In [59]:
sales_df['commission_pct'].value_counts()

commission_pct
0.03    2524
0.05    1288
0.02    1188
Name: count, dtype: int64

## <strong>Handling Duplicates using Pandas DataFrame</strong>

In [62]:
# Creating custom data for testing duplicate removal

final_data = [
    {"sale_id": 1,"sale_rep_id":101,"sale_date": "2024-01-01", "car_model": "Camry", "sale_amount": 20000, "commission_pct": 5, "sale_status": "Completed"},
    {"sale_id": 2,"sale_rep_id":102,"sale_date": "2024-01-02", "car_model": "Corolla", "sale_amount": 18000, "commission_pct": 4, "sale_status": "Completed"},
    {"sale_id": 3,"sale_rep_id":103,"sale_date": "2024-01-03","car_model": "RAV4","sale_amount": 30000,"commission_pct": 6,"sale_status": "Completed"},
    {"sale_id": 2,"sale_rep_id":102,"sale_date": "2024-01-02","car_model": "Corolla","sale_amount": 18000,"commission_pct": 4,"sale_status": "Completed"},
    {"sale_id": 4,"sale_rep_id":104,"sale_date": "2024-01-04","car_model": "Highlander","sale_amount": 35000,"commission_pct": 7,"sale_status": "Pending"},
    {"sale_id": 3,"sale_rep_id":103,"sale_date": "2024-01-03","car_model": "RAV4","sale_amount": 30000,"commission_pct": 6,"sale_status": "Completed"}
]

# Create DataFrame from the custom data
df = pd.DataFrame(final_data)

df.head(2)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,101,2024-01-01,Camry,20000,5,Completed
1,2,102,2024-01-02,Corolla,18000,4,Completed

In [65]:
# Find duplicate rows in the dataframe
df_duplicate_rows = df[df.duplicated()]

In [67]:
# Drop the duplicate rows from the dataframe
df_cleaned = df.drop_duplicates()

df_cleaned

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,101,2024-01-01,Camry,20000,5,Completed
1,2,102,2024-01-02,Corolla,18000,4,Completed
2,3,103,2024-01-03,RAV4,30000,6,Completed
4,4,104,2024-01-04,Highlander,35000,7,Pending

In [68]:
# drop duplicate rows based on sale_id column
df.drop_duplicates(subset=['sale_id'], keep='first', inplace=True)

In [69]:
df.head()

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,101,2024-01-01,Camry,20000,5,Completed
1,2,102,2024-01-02,Corolla,18000,4,Completed
2,3,103,2024-01-03,RAV4,30000,6,Completed
4,4,104,2024-01-04,Highlander,35000,7,Pending

In [70]:
# drop duplicate rows based on sale_id column
df.drop_duplicates(subset=['sale_id'], keep='last', inplace=True)

In [71]:
df

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,101,2024-01-01,Camry,20000,5,Completed
1,2,102,2024-01-02,Corolla,18000,4,Completed
2,3,103,2024-01-03,RAV4,30000,6,Completed
4,4,104,2024-01-04,Highlander,35000,7,Pending

## <strong>Rename and Reorder Columns in Pandas DataFrame</strong>

In [74]:
# Load toyota sales data without headers and assign custom column names

# list of column names
col_name = [
            'sale_id', 'sale_rep_id', 'sale_date', 'car_model', 
            'sale_amount', 'commission_pct', 'sale_status'
        ]
toyota_df  = pd.read_csv('data/toyota_sales_data_no_header.csv', header=None, names=col_name)

In [75]:
# rename the "commission_pct" column to "commission_percentage"
toyota_df.rename(columns={'commission_pct' : 'commission_percentage'}, inplace=True)

In [76]:
toyota_df.head(2)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_percentage,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending

In [77]:
# rename nultiple columns 
toyota_df.rename(columns ={'sale_rep_id' : 'sales_representative_id',
                           'sale_amount' : 'sales_amount',
                           'sale_date' : 'sales_date'}, inplace=True)

In [78]:
toyota_df.columns

Index(['sale_id', 'sales_representative_id', 'sales_date', 'car_model',
       'sales_amount', 'commission_percentage', 'sale_status'],
      dtype='object')

In [79]:
sales_rep_cleaned.head()

,rep_id,email,phone_number,region,status,full_name,hire_date_std
0,1,anthony.davis@toyota.com,-5390,North,Active,Anthony Davis,2022-07-21
1,2,edward.smith@toyota.com,-10708,North,Active,Edward Smith,2019-12-24
2,3,paul.jones@toyota.com,-2301,East,Active,Paul Jones,2022-09-06
3,4,robert.lopez@toyota.com,-8631,South,Active,Robert Lopez,2020-11-21
4,5,steven.wilson@toyota.com,-6958,West,Active,Steven Wilson,2022-03-17

In [86]:
# Reorder the columns in toyota_df dataframe
toyota_columns_reordered = ['sale_id', 'sales_representative_id', 'sales_date', 'car_model', 'sale_status', 'sales_amount',  'commission_percentage']

toyota_df = toyota_df[toyota_columns_reordered]

toyota_df.head(2)

,sale_id,sales_representative_id,sales_date,car_model,sale_status,sales_amount,commission_percentage
0,1,16,2024-11-18,Tundra,Completed,44496.88,0.05
1,2,11,2024-11-08,Tacoma,Pending,34824.72,NaN

In [91]:
# Convert all column names to upper case
toyota_df.columns = toyota_df.columns.str.upper()

In [92]:
# display the first 5 rows of toyota_df dataframe
toyota_df.head(5)

,SALE_ID,SALES_REPRESENTATIVE_ID,SALES_DATE,CAR_MODEL,SALE_STATUS,SALES_AMOUNT,COMMISSION_PERCENTAGE
0,1,16,2024-11-18,Tundra,Completed,44496.88,0.05
1,2,11,2024-11-08,Tacoma,Pending,34824.72,NaN
2,3,5,2024-11-03,Corolla,Completed,20275.08,NaN
3,4,20,2024-11-06,Corolla,Completed,20068.93,NaN
4,5,1,2024-11-26,Tundra,Completed,49811.99,0.03

## <strong>Handling Data Types in Pandas DataFrame</strong>

In [100]:
# Creating custom data based on the toyota sales data

data = [
    {"sale_id": 1,"sale_rep_id":101,"sale_date": "2024-01-01", "car_model": "Camry", "sale_amount": "20000", "commission_pct": 5, "sale_status": "Completed"},
    {"sale_id": 2,"sale_rep_id":102,"sale_date": "2024-01-02", "car_model": "Corolla", "sale_amount": "18000", "commission_pct": 4, "sale_status": "Completed"},
    {"sale_id": 3,"sale_rep_id":103,"sale_date": "2024-01-03","car_model": "RAV4","sale_amount": "30000","commission_pct": 6,"sale_status": "Completed"},
    {"sale_id": 2,"sale_rep_id":102,"sale_date": "2024-01-02","car_model": "Corolla","sale_amount": "18000","commission_pct": 4,"sale_status": "Completed"},
    {"sale_id": 4,"sale_rep_id":104,"sale_date": "2024-01-04","car_model": "Highlander","sale_amount": "35000","commission_pct": 7,"sale_status": "Pending"},
    {"sale_id": 3,"sale_rep_id":103,"sale_date": "2024-01-03","car_model": "RAV4","sale_amount": "30000","commission_pct": 6,"sale_status": "Completed"}
]

# Create DataFrame from the custom data
df = pd.DataFrame(data)

df.head(2)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,101,2024-01-01,Camry,20000,5,Completed
1,2,102,2024-01-02,Corolla,18000,4,Completed

In [101]:
# print the columns and their data types
df.dtypes

sale_id            int64
sale_rep_id        int64
sale_date         object
car_model         object
sale_amount       object
commission_pct     int64
sale_status       object
dtype: object

In [109]:
#  standardize sale_date columns to datetime format
df['sale_date'] = pd.to_datetime(df['sale_date'], format='%Y-%m-%d')

In [105]:
# standardize sale_amount column to numeric data type
df['sale_amount'] = pd.to_numeric(df['sale_amount'], errors='coerce')

In [110]:
# data types after standardization
df.dtypes

sale_id                    int64
sale_rep_id                int64
sale_date         datetime64[ns]
car_model                 object
sale_amount                int64
commission_pct             int64
sale_status               object
dtype: object

In [112]:
# convert car_model, sale_status columns to categorical data type
df['car_model'] = df['car_model'].astype('category')
df['sale_status'] = df['sale_status'].astype('category')

In [114]:
df.dtypes

sale_id                    int64
sale_rep_id                int64
sale_date         datetime64[ns]
car_model               category
sale_amount                int64
commission_pct             int64
sale_status             category
dtype: object

In [115]:
df.nunique()

sale_id           4
sale_rep_id       4
sale_date         4
car_model         4
sale_amount       4
commission_pct    4
sale_status       2
dtype: int64

## <strong>Filetring and Subsetting Data in Pandas DataFrames</strong>

In [116]:
# Load toyota sales data
sales_df = pd.read_csv('data/toyota_sales_data.csv', low_memory=False)

In [117]:
# stanardize sale_date column to datetime format
sales_df['sale_date'] = pd.to_datetime(sales_df['sale_date'])

In [118]:
# Data types after standardization
sales_df.dtypes

sale_id                    int64
sale_rep_id                int64
sale_date         datetime64[ns]
car_model                 object
sale_amount              float64
commission_pct           float64
sale_status               object
dtype: object

In [124]:
# filtering data where sale amount is greater than 30000 and car model is RAV4
high_sales_rav4_df = sales_df[(sales_df['sale_amount'] > 30000) & (sales_df['car_model'] == 'RAV4')]

high_sales_rav4_df.shape

(519, 7)

In [ ]:
# Filtering data where sale amount is greater than 30000 and sale status is completed using .loc method
sales_df.loc[
    (sales_df['sale_amount'] > 30000) & (sales_df['sale_status'] == 'Completed'),
    ['sale_rep_id', 'car_model', 'sale_amount', 'commission_pct', 'sale_date', 'sale_status']
    ]

,sale_rep_id,car_model,sale_amount,commission_pct,sale_date,sale_status
0,16,Tundra,44496.88,0.05,2024-11-18,Completed
4,1,Tundra,49811.99,0.03,2024-11-26,Completed
5,14,RAV4,34346.20,0.03,2024-11-28,Completed
6,12,RAV4,33073.24,0.03,2024-11-30,Completed
10,12,Highlander,40044.87,0.02,2024-11-11,Completed
...,...,...,...,...,...,...
4988,20,RAV4,31543.36,0.02,2024-11-04,Completed
4989,10,Tundra,38116.14,0.02,2024-11-15,Completed
4990,20,Highlander,36500.60,NaN,2024-11-17,Completed
4992,10,Tundra,47497.87,0.02,2024-11-26,Completed
4997,18,Tacoma,30780.39,0.02,2024-11-06,Completed

In [135]:
# Filtering data where sale amount is greater than 30000 and car model is RAV4 and sale status is completed using .query method
toyota__high_sales_rav4_completed = sales_df.query('sale_amount > 30000 and car_model == "RAV4" and sale_status == "Completed"')\
    [['sale_rep_id', 'sale_date', 'car_model', 'sale_amount', 'commission_pct', 'sale_status']]

toyota__high_sales_rav4_completed.head(10)

     sale_rep_id  sale_date car_model  sale_amount  commission_pct sale_status
5             14 2024-11-28      RAV4     34346.20            0.03   Completed
6             12 2024-11-30      RAV4     33073.24            0.03   Completed
17             8 2024-11-02      RAV4     32751.81             NaN   Completed
28             2 2024-11-19      RAV4     30624.47             NaN   Completed
29             2 2024-11-20      RAV4     31643.54             NaN   Completed
31             2 2024-11-07      RAV4     32250.04             NaN   Completed
86            19 2024-11-18      RAV4     33610.01            0.03   Completed
110           14 2024-11-04      RAV4     32369.50            0.05   Completed
116            3 2024-11-03      RAV4     30514.65            0.02   Completed
133           16 2024-11-24      RAV4     34922.10            0.05   Completed

## <strong>Sorting Data in Pandas DataFrame</strong>

In [140]:
sales_df.dtypes

sale_id                    int64
sale_rep_id                int64
sale_date         datetime64[ns]
car_model                 object
sale_amount              float64
commission_pct           float64
sale_status               object
dtype: object

In [142]:
# sorting data by sale amount in ascending order
sales_df.sort_values(by='sale_amount')[['sale_rep_id', 'car_model', 'sale_amount', 'commission_pct', 'sale_date', 'sale_status']].head(10)

,sale_rep_id,car_model,sale_amount,commission_pct,sale_date,sale_status
2275,12,Corolla,20000.94,0.05,2024-11-08,Pending
2464,16,Corolla,20001.20,0.05,2024-11-02,Completed
2488,16,Corolla,20001.37,0.02,2024-11-27,Pending
2871,2,Corolla,20003.27,0.05,2024-11-16,Completed
4910,6,Corolla,20004.62,0.03,2024-11-23,Completed
3554,15,Corolla,20017.71,0.02,2024-11-07,Completed
2211,20,Corolla,20026.22,0.05,2024-11-19,Pending
3716,13,Corolla,20038.33,NaN,2024-11-10,Completed
2352,8,Corolla,20039.54,NaN,2024-11-01,Completed
4378,11,Corolla,20044.54,0.05,2024-11-22,Completed

In [143]:
# Sorting data by sales amount in descending order
sales_df.sort_values(by='sale_amount', ascending=False)[['sale_rep_id', 'car_model', 'sale_amount', 'commission_pct', 'sale_date', 'sale_status']].head(10)

,sale_rep_id,car_model,sale_amount,commission_pct,sale_date,sale_status
2877,15,Tundra,49995.68,NaN,2024-11-02,Pending
685,8,Tundra,49979.12,0.02,2024-11-17,Completed
1901,3,Tundra,49974.88,0.02,2024-11-12,Cancelled
3934,6,Tundra,49942.26,0.05,2024-11-27,Completed
2577,7,Tundra,49923.84,0.02,2024-11-18,Completed
3041,10,Tundra,49916.96,0.02,2024-11-23,Completed
3647,4,Tundra,49907.66,NaN,2024-11-10,Completed
1997,1,Tundra,49896.99,0.05,2024-11-07,Cancelled
3287,19,Tundra,49868.47,0.03,2024-11-26,Completed
4002,19,Tundra,49828.45,0.03,2024-11-28,Completed

In [145]:
# Sort data by car model and sale date descending order
sales_df.sort_values(by = ['car_model', 'sale_date'], ascending=[True, False])[['sale_rep_id', 'car_model', 'sale_amount', 'commission_pct', 'sale_date', 'sale_status']].head(10)

,sale_rep_id,car_model,sale_amount,commission_pct,sale_date,sale_status
725,4,Camry,26379.41,0.05,2024-11-30,Completed
1024,18,Camry,26696.07,0.03,2024-11-30,Completed
1624,6,Camry,26085.51,NaN,2024-11-30,Pending
1837,2,Camry,27058.25,0.03,2024-11-30,Completed
1874,20,Camry,29408.34,NaN,2024-11-30,Completed
1877,4,Camry,29068.47,0.02,2024-11-30,Completed
2004,17,Camry,27100.00,0.05,2024-11-30,Completed
2254,2,Camry,27294.52,0.03,2024-11-30,Completed
2389,16,Camry,26517.58,NaN,2024-11-30,Pending
2566,15,Camry,26034.93,0.03,2024-11-30,Completed

In [147]:
# Filter latest purcahse for each car model
sales_df.sort_values(by=['car_model', 'sale_date'], ascending = [True, False])\
    .drop_duplicates(subset=['car_model'], keep='first')\
    [['sale_rep_id', 'car_model', 'sale_amount', 'commission_pct', 'sale_date', 'sale_status']]

,sale_rep_id,car_model,sale_amount,commission_pct,sale_date,sale_status
725,4,Camry,26379.41,0.05,2024-11-30,Completed
351,7,Corolla,20570.36,0.03,2024-11-30,Completed
151,16,Highlander,37248.17,0.05,2024-11-30,Completed
6,12,RAV4,33073.24,0.03,2024-11-30,Completed
72,5,Tacoma,33284.96,0.05,2024-11-30,Completed
115,3,Tundra,45031.33,0.05,2024-11-30,Completed

In [152]:
# Find maximum and minimum sales value, commission value for each car model
sales_df.groupby('car_model')[['sale_amount', 'commission_pct']].agg(['sum', 'max', 'min'])

            sale_amount                     commission_pct
                    sum       max       min            sum   max   min
car_model
Camry       23515068.85  29981.84  25006.17          20.50  0.05  0.02
Corolla     18559680.22  24996.35  20000.94          21.15  0.05  0.02
Highlander  32562337.53  44975.88  35008.84          21.07  0.05  0.02
RAV4        26647722.94  34965.01  27002.66          21.56  0.05  0.02
Tacoma      28908731.32  39994.13  30011.69          20.89  0.05  0.02
Tundra      34705000.21  49995.68  35026.61          20.49  0.05  0.02

## <strong>Custom DataFrames and Advnaced Concepts</strong>

In [155]:
# Create custom data similar to toyota sales data for testing also add protity value column for all the rows

data = [
    {"sale_id": 1,"sale_rep_id":101,"sale_date": "2024-01-01", "car_model": "Camry", "sale_amount": 20000, "commission_pct": 5, "sale_status": "Completed", "priority": "High"},
    {"sale_id": 2,"sale_rep_id":102,"sale_date": "2024-01-02", "car_model": "Corolla", "sale_amount": 18000, "commission_pct": 4, "sale_status": "Completed", "priority": "Medium"},
    {"sale_id": 3,"sale_rep_id":103,"sale_date": "2024-01-03","car_model": "RAV4","sale_amount": 30000,"commission_pct": 6,"sale_status": "Completed", "priority": "High"},
    {"sale_id": 2,"sale_rep_id":102,"sale_date": "2024-01-02","car_model": "Corolla","sale_amount": 18000,"commission_pct": 4,"sale_status": "Completed", "priority": "Medium"},
    {"sale_id": 4,"sale_rep_id":104,"sale_date": "2024-01-04","car_model": "Highlander","sale_amount": 35000,"commission_pct": 7,"sale_status": "Pending", "priority": "Low"},
    {"sale_id": 3,"sale_rep_id":103,"sale_date": "2024-01-03","car_model": "RAV4","sale_amount": 30000,"commission_pct": 6,"sale_status": "Completed", "priority": "High"}
    ]

# Create DataFrame from the custom data
df = pd.DataFrame(data)

# display the first 5 rows of the dataframe
df.head()

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status,priority
0,1,101,2024-01-01,Camry,20000,5,Completed,High
1,2,102,2024-01-02,Corolla,18000,4,Completed,Medium
2,3,103,2024-01-03,RAV4,30000,6,Completed,High
3,2,102,2024-01-02,Corolla,18000,4,Completed,Medium
4,4,104,2024-01-04,Highlander,35000,7,Pending,Low

In [159]:
# drop duplicate rows based on sale_id column and keep the last occurrence
dedup_df = df.drop_duplicates(subset=['sale_id'], keep='last')[['sale_id', 'sale_rep_id', 'sale_date', 'car_model', 'sale_amount', 'priority', 'sale_status']]

dedup_df

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,priority,sale_status
0,1,101,2024-01-01,Camry,20000,High,Completed
3,2,102,2024-01-02,Corolla,18000,Medium,Completed
4,4,104,2024-01-04,Highlander,35000,Low,Pending
5,3,103,2024-01-03,RAV4,30000,High,Completed

In [161]:
# sort data by priority columnn 
dedup_df.sort_values(by = 'priority', ascending=True)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,priority,sale_status
0,1,101,2024-01-01,Camry,20000,High,Completed
5,3,103,2024-01-03,RAV4,30000,High,Completed
4,4,104,2024-01-04,Highlander,35000,Low,Pending
3,2,102,2024-01-02,Corolla,18000,Medium,Completed

In [163]:
# Sort data by priority columns in High, Medium, Low order
priority_order = ['High', 'Medium', 'Low']

custom_priority_dtype = pd.CategoricalDtype(categories=priority_order, ordered=True)

In [165]:
dedup_df['priority'] = dedup_df['priority'].astype(custom_priority_dtype)

dedup_df.sort_values(by = 'priority', ascending=False)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,priority,sale_status
4,4,104,2024-01-04,Highlander,35000,Low,Pending
3,2,102,2024-01-02,Corolla,18000,Medium,Completed
0,1,101,2024-01-01,Camry,20000,High,Completed
5,3,103,2024-01-03,RAV4,30000,High,Completed

# <strong>Introduction: Joining or Merging DataFrames</strong>

## <strong>Joining and Merging Datasets in Pandas</strong>

#### <strong> Different types of Joins</strong>:
1. Inner Join
2. Left Join
3. Right Join
4. Outer Join

#### <strong> Best Practices for Joins </strong>
1. Specify the parent table first
2. Validate Keys
3. Inspect missing data

#### <strong>Related to SQL</strong>

| JoinTpe     | SQL Equivalent     | Pandas how Parameters      |
|-------------|--------------------|----------------------------|
| Left Join   | LEFT OUTER JOIN    | how= 'left'                |
| Tight Join  | RIGHT OUTER JOIN   | how= 'right'               |
| Outer Join  | FULL OUTER JOIN    | how= 'outer'               |

#### <strong>Parent-Child Relationships in Joins</strong>

#### <strong>Sales Representatives Table (sales_reps)</strong>

| rep_id | name     | region      |
|--------|----------|-------------|
| 1      | Alice    | North       |
| 2      | Bob      | South       |
| 3      | Charlie  | West        |

#### <strong>Sales Data Table (sales) </strong>

|  sale_id | sale_rep_id | sale_amount |
|----------|-------------|-------------|
| 101      | 1           | 500         |
| 102      | 2           | 1000        |
| 103      | NaN         | 750         |
| 104      | 4           | 1200        |

#### <strong> Inner Join Results </strong>

#### <strong> Left Join Results </strong>

#### <strong> Right Join Results </strong>

#### <strong> Outer Join Results </strong>

## <strong>Inner Join in Pandas DataFrame</strong>

In [167]:
# crete custome sales rep and sales data for testing merge and join operations
# sales rep data
sales_rep_data = [
    {"sale_rep_id": 101, "first_name": "John", "last_name": "Doe", "region": "North", "hire_date": "01/15/2020"},
    {"sale_rep_id": 102, "first_name": "Jane", "last_name": "Smith", "region": "South", "hire_date": "03/22/2019"},
    {"sale_rep_id": 103, "first_name": "Emily", "last_name": "Johnson", "region": "East", "hire_date": "07/30/2021"},
    {"sale_rep_id": 104, "first_name": "Michael", "last_name": "Brown", "region": "West", "hire_date": "11/05/2018"}
]
# sales data
sales_data = [
    {"sale_id": 1,"sale_rep_id":101,"sale_date": "2024-01-01", "car_model": "Camry", "sale_amount": 20000, "commission_pct": 5, "sale_status": "Completed"},
    {"sale_id": 2,"sale_rep_id":102,"sale_date": "2024-01-02", "car_model": "Corolla", "sale_amount": 18000, "commission_pct": 4, "sale_status": "Completed"},
    {"sale_id": 3,"sale_rep_id":None,"sale_date": "2024-01-03","car_model": "RAV4","sale_amount": 30000,"commission_pct": 6,"sale_status": "Completed"},
    {"sale_id": 4,"sale_rep_id":104,"sale_date": "2024-01-04","car_model": "Highlander","sale_amount": 35000,"commission_pct": 7,"sale_status": "Pending"}
    ]

# Create DataFrame from the custom data
sales_rep_df = pd.DataFrame(sales_rep_data)
sales_data_df = pd.DataFrame(sales_data)

In [ ]:
# join sales data with sales rep data using inner join
# methode 1: using merge function
merge_df = pd.merge(
    sales_rep_df,
    sales_data_df,
    left_on="sale_rep_id",
    right_on="sale_rep_id",
    how="inner"
    )

merge_df.head()

,sale_rep_id,first_name,last_name,region,hire_date,sale_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,101,John,Doe,North,01/15/2020,1,2024-01-01,Camry,20000,5,Completed
1,102,Jane,Smith,South,03/22/2019,2,2024-01-02,Corolla,18000,4,Completed
2,104,Michael,Brown,West,11/05/2018,4,2024-01-04,Highlander,35000,7,Pending

In [170]:
# methode 2: using join function
join_df = sales_rep_df.merge(
    sales_data_df,
    on = 'sale_rep_id',
    how='inner'
    )

join_df.head()

,sale_rep_id,first_name,last_name,region,hire_date,sale_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,101,John,Doe,North,01/15/2020,1,2024-01-01,Camry,20000,5,Completed
1,102,Jane,Smith,South,03/22/2019,2,2024-01-02,Corolla,18000,4,Completed
2,104,Michael,Brown,West,11/05/2018,4,2024-01-04,Highlander,35000,7,Pending

In [172]:
# group the merged data by region and calculate the total sales amount for each region
merge_df.groupby('region')[['sale_amount']].sum()

        sale_amount
region
North         20000
South         18000
West          35000

## <strong>Left and Right Joins with Pandas DataFrames</strong>

In [ ]:
# left join sales data with sales rep data using merge function
left_join_df = pd.merge(
    sales_rep_df,
    sales_data_df,
    left_on="sale_rep_id",
    right_on="sale_rep_id",
    how="left"
    )

print(left_join_df)

   sale_rep_id first_name last_name region   hire_date  sale_id   sale_date  \
0          101       John       Doe  North  01/15/2020      1.0  2024-01-01
1          102       Jane     Smith  South  03/22/2019      2.0  2024-01-02
2          103      Emily   Johnson   East  07/30/2021      NaN         NaN
3          104    Michael     Brown   West  11/05/2018      4.0  2024-01-04

    car_model  sale_amount  commission_pct sale_status
0       Camry      20000.0             5.0   Completed
1     Corolla      18000.0             4.0   Completed
2         NaN          NaN             NaN         NaN
3  Highlander      35000.0             7.0     Pending

In [184]:
inactive_reps = left_join_df[left_join_df['sale_id'].isnull()]

inactive_reps

,sale_rep_id,first_name,last_name,region,hire_date,sale_id,sale_date,car_model,sale_amount,commission_pct,sale_status
2,103,Emily,Johnson,East,07/30/2021,NaN,NaN,NaN,NaN,NaN,NaN

In [177]:
# right join sales data with sales rep data using merge function
right_join_df = pd.merge(
    sales_rep_df,
    sales_data_df,
    left_on="sale_rep_id",
    right_on="sale_rep_id",
    how="right"
    )

right_join_df

,sale_rep_id,first_name,last_name,region,hire_date,sale_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,101.0,John,Doe,North,01/15/2020,1,2024-01-01,Camry,20000,5,Completed
1,102.0,Jane,Smith,South,03/22/2019,2,2024-01-02,Corolla,18000,4,Completed
2,NaN,NaN,NaN,NaN,NaN,3,2024-01-03,RAV4,30000,6,Completed
3,104.0,Michael,Brown,West,11/05/2018,4,2024-01-04,Highlander,35000,7,Pending

## <strong>Outer Join with Pandas DataFrame</strong>

In [187]:
# outer join sales data with sales rep data using merge function
outer_join_df = pd.merge(
    sales_rep_df,
    sales_data_df,
    left_on="sale_rep_id",
    right_on="sale_rep_id",
    how="outer"
    )

# find the inactive sales representatives who have no sales transactions using left join result
inactive_reps = left_join_df[left_join_df['sale_id'].isnull()]
inactive_reps

# find the sales transactions that have no corresponding sales representative using right join result
sales_without_reps = right_join_df[right_join_df['first_name'].isnull()]
sales_without_reps

,sale_rep_id,first_name,last_name,region,hire_date,sale_id,sale_date,car_model,sale_amount,commission_pct,sale_status
2,NaN,NaN,NaN,NaN,NaN,3,2024-01-03,RAV4,30000,6,Completed

In [192]:
# Sample data to test join and merge operations based on two columns: sale_rep_id and region
# Please add region column to sales data for testing merge and join operations based on two columns: sale_rep_id and region
# sales rep data
sales_rep_data = [
    {"sale_rep_id": 101, "first_name": "John", "last_name": "Doe", "region": "North", "hire_date": "01/15/2020"},
    {"sale_rep_id": 102, "first_name": "Jane", "last_name": "Smith", "region": "South", "hire_date": "03/22/2019"},
    {"sale_rep_id": 103, "first_name": "Emily", "last_name": "Johnson", "region": "East", "hire_date": "07/30/2021"},
    {"sale_rep_id": 104, "first_name": "Michael", "last_name": "Brown", "region": "West", "hire_date": "11/05/2018"}
]   
# sales data
sales_data = [
    {"sale_id": 1,"sale_rep_id":101,"sale_date": "2024-01-01", "car_model": "Camry", "sale_amount": 20000, "commission_pct": 5, "sale_status": "Completed", "region": "North"},
    {"sale_id": 2,"sale_rep_id":102,"sale_date": "2024-01-02", "car_model": "Corolla", "sale_amount": 18000, "commission_pct": 4, "sale_status": "Completed", "region": "South"},
    {"sale_id": 3,"sale_rep_id":103,"sale_date": "2024-01-03","car_model": "RAV4","sale_amount": 30000,"commission_pct": 6,"sale_status": "Completed", "region": "East"},
    {"sale_id": 4,"sale_rep_id":104,"sale_date": "2024-01-04","car_model": "Highlander","sale_amount": 35000,"commission_pct": 7,"sale_status": "Pending", "region": "West"},
    {"sale_id": 5,"sale_rep_id":101,"sale_date": "2024-01-05","car_model": "Camry","sale_amount": 22000,"commission_pct": 5.5,"sale_status": "Completed", "region":"North"},
    {"sale_id": 6,"sale_rep_id":102,"sale_date": "2024-01-06","car_model":"Corolla","sale_amount" : 19000,	"commission_pct" : 4.5,	"sale_status" :	"Completed",	"region":"South"},
    {"sale_id": 7,"sale_rep_id":103,"sale_date": "2024-01-07","car_model": "RAV4","sale_amount": 32000,"commission_pct": 6.5,"sale_status": "Completed", "region": "East"},
    {"sale_id": 8,"sale_rep_id":104,"sale_date": "2024-01-08","car_model": "Highlander","sale_amount": 36000,"commission_pct": 7.5,"sale_status": "Pending", "region": "West"}
]

# Create DataFrame from the custom data
sales_rep_df = pd.DataFrame(sales_rep_data) 
sales_data_df = pd.DataFrame(sales_data)

In [ ]:
# Inner join sales data with sales rep data using merge function based on sale_rep_id and region columns
# Method` 1: using merge function`
merge_df = pd.merge(
    sales_rep_df,
    sales_data_df,
    left_on=["sale_rep_id", "region"],
    right_on=["sale_rep_id", "region"],
    how="inner"
    )   

merge_df.head()

,sale_rep_id,first_name,last_name,region,hire_date,sale_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,101,John,Doe,North,01/15/2020,1,2024-01-01,Camry,20000,5.0,Completed
1,101,John,Doe,North,01/15/2020,5,2024-01-05,Camry,22000,5.5,Completed
2,102,Jane,Smith,South,03/22/2019,2,2024-01-02,Corolla,18000,4.0,Completed
3,102,Jane,Smith,South,03/22/2019,6,2024-01-06,Corolla,19000,4.5,Completed
4,103,Emily,Johnson,East,07/30/2021,3,2024-01-03,RAV4,30000,6.0,Completed

In [194]:
# method 2: using join function
join_df = sales_rep_df.merge(
    sales_data_df,
    on = ['sale_rep_id', 'region'],
    how='inner'
    )

join_df.head()

,sale_rep_id,first_name,last_name,region,hire_date,sale_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,101,John,Doe,North,01/15/2020,1,2024-01-01,Camry,20000,5.0,Completed
1,101,John,Doe,North,01/15/2020,5,2024-01-05,Camry,22000,5.5,Completed
2,102,Jane,Smith,South,03/22/2019,2,2024-01-02,Corolla,18000,4.0,Completed
3,102,Jane,Smith,South,03/22/2019,6,2024-01-06,Corolla,19000,4.5,Completed
4,103,Emily,Johnson,East,07/30/2021,3,2024-01-03,RAV4,30000,6.0,Completed

## <strong>Join Two CSV Files Using Pandas</strong>

In [196]:
# load toyota sales data and sales rep data from the csv files
# Please note that these are recently edited files. Do not suggest code that has been deleted.

# load sales data
sales_df = pd.read_csv('data/toyota_sales_data.csv', low_memory=False)
print(sales_df.columns)
print()
# load sales rep data
sales_rep = pd.read_csv('data/sales_reps_data.csv', low_memory=False)
print(sales_rep.columns)

Index(['sale_id', 'sale_rep_id', 'sale_date', 'car_model', 'sale_amount',
       'commission_pct', 'sale_status'],
      dtype='object')

Index(['rep_id', 'first_name', 'last_name', 'email', 'phone_number',
       'hire_date', 'region', 'status'],
      dtype='object')

In [207]:
# Join sales data with sales rep data using inner join based on sale_rep_id columns
# method 1: using merge function
outer_join_df = pd.merge(
    sales_rep,
    sales_df,
    left_on="rep_id",
    right_on="sale_rep_id",
    how="outer"
    )

In [208]:
# display shape of left join result
outer_join_df.shape

(5002, 15)

In [209]:
# find the inactive sales representatives who have no sales transactions using left join result
inactive_reps = outer_join_df[outer_join_df['sale_id'].isnull()][['rep_id', 'first_name', 'last_name', 'region']]

inactive_reps

      rep_id first_name last_name   region
5000      21        Tom      Kyte  Unknown
5001      22      Scott     Tiger  Unknown

In [212]:
# Find the sales transactions that have no corresponding sales representative using right join result
transactions_with_no_rep = outer_join_df[outer_join_df['rep_id'].isnull()]

In [217]:
# Find Sales value and number of transactions by region
outer_join_df.groupby(['region'])['sale_amount'].agg(['sum', 'count'])

                 sum  count
region
East     32522735.85    986
North    83454943.52   2526
South    15741755.51    479
Unknown         0.00      0
West     33179106.19   1009

In [220]:
# Find the Sales value by rep name
outer_join_df['rep_name'] = outer_join_df['last_name'] + ' ' + outer_join_df['first_name']

rep_sales = outer_join_df.groupby(['rep_name'])['sale_amount'].sum().round(2).reset_index()

rep_sales

             rep_name  sale_amount
0   Brown Christopher   7822524.30
1       Davis Anthony   8793624.75
2         Davis David   8672081.85
3      Gonzalez David   7946648.50
4    Hernandez Robert   8012200.98
5      Jackson Daniel   8493429.13
6   Jones Christopher   8658437.14
7        Jones Edward   7849573.71
8          Jones Paul   7483168.82
9            Kyte Tom         0.00
10      Lopez Charles   8247398.75
11       Lopez Robert   7473215.23
12     Martinez Brian   8089256.01
13    Martinez Daniel   8759602.34
14   Martinez Michael   8161330.01
15      Moore William   8218385.64
16       Smith Edward   8721864.31
17       Smith Thomas   8623533.39
18        Tiger Scott         0.00
19    Williams Daniel   8268540.28
20      Wilson Steven   7814744.92
21      Wilson Thomas   8788981.01

In [225]:
# find top 2 resps by sales value
top_2_reps = rep_sales.sort_values(by ='sale_amount', ascending=False).head(2)
top_2_reps

         rep_name  sale_amount
1   Davis Anthony   8793624.75
21  Wilson Thomas   8788981.01

In [229]:
# Top Nth Sales rep name by sales value
top_n = 6
top_n_reps = rep_sales.sort_values(by='sale_amount', ascending=False).head(top_n).tail(1)
top_n_reps

            rep_name  sale_amount
6  Jones Christopher   8658437.14

In [ ]:
# nlargeth to find top N sales reps by sales value
# Method 1: using nlargest function
n = 3
top_nth_rep = rep_sales.nlargest(n, 'sale_amount').iloc[-1]
print(f'nth method: ', top_nth_rep)
print()

# Method 2: using sort_values function
top_nth_rep_sort = rep_sales.sort_values(by='sale_amount', ascending=False).head(n).tail(1)
print(f'sort_values method: ', top_nth_rep_sort)
print()

# Method 3: using sort_values with loc function
top_nth_rep_loc = rep_sales.sort_values(by='sale_amount', ascending=False).loc[n-1]


# Method 4: using rank function
rep_sales['rank'] = rep_sales['sale_amount'].rank(method='dense', ascending=False)
top_nth_rep_rank = rep_sales[rep_sales['rank'] == n]
print(f'rank method: ', top_nth_rep_rank)
print()

nth method:  rep_name       Martinez Daniel
sale_amount         8759602.34
Name: 13, dtype: object

sort_values method:             rep_name  sale_amount
13  Martinez Daniel   8759602.34

rank method:             rep_name  sale_amount  rank
13  Martinez Daniel   8759602.34   3.0

In [238]:
rep_sales.sort_values(by='sale_amount', ascending=False).loc[n-1]

rep_name       Davis David
sale_amount     8672081.85
rank                   5.0
Name: 2, dtype: object

# <strong> Data Transformations and Processing </strong>

## <strong> Groupping and Aggregating Functions </strong>

In [242]:
# Calculate total sales value by each sales representative
outer_join_df.groupby('rep_name')['sale_amount'].sum().round(2).reset_index()

             rep_name  sale_amount
0   Brown Christopher   7822524.30
1       Davis Anthony   8793624.75
2         Davis David   8672081.85
3      Gonzalez David   7946648.50
4    Hernandez Robert   8012200.98
5      Jackson Daniel   8493429.13
6   Jones Christopher   8658437.14
7        Jones Edward   7849573.71
8          Jones Paul   7483168.82
9            Kyte Tom         0.00
10      Lopez Charles   8247398.75
11       Lopez Robert   7473215.23
12     Martinez Brian   8089256.01
13    Martinez Daniel   8759602.34
14   Martinez Michael   8161330.01
15      Moore William   8218385.64
16       Smith Edward   8721864.31
17       Smith Thomas   8623533.39
18        Tiger Scott         0.00
19    Williams Daniel   8268540.28
20      Wilson Steven   7814744.92
21      Wilson Thomas   8788981.01

In [244]:
# calculate total sales value and average sales value by each sales representative
sales_summary = outer_join_df.groupby('rep_name').agg({'sale_amount': ['sum', 'mean'], 'sale_id': ['count']}).round(2)
sales_summary.columns = ['total_sales', 'average_sales', 'number_of_transactions']
sales_summary.reset_index()
sales_summary

                   total_sales  average_sales  number_of_transactions
rep_name
Brown Christopher   7822524.30       33429.59                     234
Davis Anthony       8793624.75       32934.92                     267
Davis David         8672081.85       33612.72                     258
Gonzalez David      7946648.50       32435.30                     245
Hernandez Robert    8012200.98       33384.17                     240
Jackson Daniel      8493429.13       33438.70                     254
Jones Christopher   8658437.14       32673.35                     265
Jones Edward        7849573.71       33402.44                     235
Jones Paul          7483168.82       33556.81                     223
Kyte Tom                  0.00            NaN                       0
Lopez Charles       8247398.75       32858.16                     251
Lopez Robert        7473215.23       32073.89                     233
Martinez Brian      8089256.01       33705.23                     240
Martinez Daniel     8759602.34       32930.84                     266
Martinez Michael    8161330.01       32131.22                     254
Moore William       8218385.64       32873.54                     250
Smith Edward        8721864.31       32788.96                     266
Smith Thomas        8623533.39       32789.10                     263
Tiger Scott               0.00            NaN                       0
Williams Daniel     8268540.28       33611.95                     246
Wilson Steven       7814744.92       32426.33                     241
Wilson Thomas       8788981.01       32672.79                     269

## <strong> Advanced Aggregation Using Pandas </strong>

In [ ]:
# Calculate total sales amount by car model
sales_df.groupby('car_model')['sale_amount'].sum()

car_model
Camry         23515068.85
Corolla       18559680.22
Highlander    32562337.53
RAV4          26647722.94
Tacoma        28908731.32
Tundra        34705000.21
Name: sale_amount, dtype: float64

In [259]:
# calculate total and average sales value by car model
sales_by_car_model = sales_df.groupby('car_model')['sale_amount'].agg(['sum', 'mean']).round(2).reset_index()
# rename columns
print('Before renaming columns:')
print(sales_by_car_model.columns)
print()

sales_by_car_model.columns = ['car_model', 'total_sales', 'average_sales']
print('After renaming columns:')
print(sales_by_car_model.columns)

Before renaming columns:
Index(['car_model', 'sum', 'mean'], dtype='object')

After renaming columns:
Index(['car_model', 'total_sales', 'average_sales'], dtype='object')

In [265]:
# caluclaute multiple statistics by car model
sales_stats_by_car_model = sales_df.groupby('car_model')\
            .agg({'sale_amount': ['sum', 'mean', 'median'], 'sale_id': ['count']})\
            .round(2).reset_index()

# rename columns
sales_stats_by_car_model.columns = ['car_model', 'total_sales', 'average_sales', 'median_sales', 'number_of_transactions']

# display the final result
sales_stats_by_car_model

,car_model,total_sales,average_sales,median_sales,number_of_transactions
0,Camry,23515068.85,27470.87,27448.58,856
1,Corolla,18559680.22,22442.18,22477.28,827
2,Highlander,32562337.53,40002.87,39988.89,814
3,RAV4,26647722.94,30985.72,30922.64,860
4,Tacoma,28908731.32,34998.46,34989.82,826
5,Tundra,34705000.21,42478.58,42306.67,817

In [271]:
# caluclaute multiple statistics by car model
sales_stats_by_region = sales_df.groupby('car_model')\
                .agg(total_sales=("sale_amount","sum"),\
                     average_sale=("sale_amount", "mean"),\
                     tot_transactions=("sale_id", "count"))\
                .round(2).reset_index()

# display the final result
sales_stats_by_region

    car_model  total_sales  average_sale  tot_transactions
0       Camry  23515068.85      27470.87               856
1     Corolla  18559680.22      22442.18               827
2  Highlander  32562337.53      40002.87               814
3        RAV4  26647722.94      30985.72               860
4      Tacoma  28908731.32      34998.46               826
5      Tundra  34705000.21      42478.58               817

## <strong> Custom Aggregation Functions </strong>

In [273]:
sales_by_rep_8 = sales_df.query("sale_rep_id == 8")

sales_by_rep_8

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
17,18,8,2024-11-02,RAV4,32751.81,NaN,Completed
55,56,8,2024-11-21,Highlander,39603.90,NaN,Completed
87,88,8,2024-11-04,Tacoma,34140.12,NaN,Completed
122,123,8,2024-11-01,Highlander,40575.11,0.02,Completed
131,132,8,2024-11-06,Tacoma,37307.80,0.02,Completed
...,...,...,...,...,...,...,...
4925,4926,8,2024-11-16,Highlander,39606.12,0.03,Completed
4931,4932,8,2024-11-21,Highlander,35182.30,0.05,Completed
4961,4962,8,2024-11-24,Tundra,40757.21,0.02,Completed
4983,4984,8,2024-11-04,Tacoma,30443.79,NaN,Pending
4996,4997,8,2024-11-11,Camry,26519.24,0.05,Pending